// Part of the Site & Pattern 3D viewer, split out of the former
// single html/scene3d.html <script> (V2.24). Loaded as an ordered
// CLASSIC script by the bootstrap in scene3d.html — it shares the
// global scope with its siblings (THREE/OrbitControls/mergeGeometries
// are globals set by the bootstrap), so load ORDER is dependency
// order. Do not add ES `import`/`export` here.

// ── Blender-authored GLB model assets (V2.27) ───────────────────────────────
// Loads the low-poly GLB archetypes generated by scripts/blender/assetlib
// (committed under html/assets/models/) and serves them to the plant and
// wildlife builders through the window.glb* lookups below. The procedural
// geometry in chunks 02–04/07 is the PERMANENT fallback, not a transition:
// every lookup returns null until (and unless) the manifest and its files
// load, and any per-file failure just leaves that archetype procedural.
// Contract with the generator (see docs/3D_ASSETS.md):
//   · plants: unit frame (base y=0, height 1) — re-normalised here with the
//     same normalizeUnit() the procedural builders use; mesh parts named
//     'bark' / 'foliage'; COLOR_0 is grayscale AO so the per-instance
//     seasonal/health/presence tints multiply through unchanged.
//   · imported materials are DISCARDED — geometry marries the viewer's own
//     plantMaterial instances (wind sway, vertexColors, shared in MATS).
//   · fauna: one template per kind with named nodes (WingL/WingR pivots at
//     the hinge, Band0..2, Spots, Beak…) and named materials (MatFuzz,
//     MatBody…) that map onto the existing per-species appearance bags.
// This chunk registers NO window.perma* hooks (the bridge contract in
// tests/test_bridge_contract.py pins viewer hooks to map3d_js builders).

let MODEL_STATE = 'loading';        // 'loading' | 'ready' | 'absent'
const MODEL_PLANTS = new Map();     // manifest key → {tiers:{n:{bark,foliage}}} | {parts} | {variants:[geo]}
const MODEL_FAUNA = new Map();      // fauna key → {template, spec}
const MODEL_STRUCTS = new Map();    // struct_id → {template, spec}
let MODEL_COUNTS = null;            // {plants, fauna} once ready (for the log line)

// Every GLB master geometry, so disposeDesignGroup can protect them the same
// way it protects the procedural archetype caches (a quality change clears
// those caches, and without this the masters inside the old design group
// would be disposed and the next rebuild would instance dead geometry).
window.glbSharedGeos = function () {
  const out = [];
  for (const rec of MODEL_PLANTS.values()) {
    if (rec.tiers) for (const t of Object.values(rec.tiers)) {
      if (t.bark) out.push(t.bark);
      if (t.foliage) out.push(t.foliage);
    }
    if (rec.variants) for (const p of rec.variants) {
      if (p.bark) out.push(p.bark);
      if (p.foliage) out.push(p.foliage);
    }
    if (rec.parts) {
      if (rec.parts.bark) out.push(rec.parts.bark);
      if (rec.parts.foliage) out.push(rec.parts.foliage);
    }
  }
  return out;
};

// ── loading ─────────────────────────────────────────────────────────────────

// Bake a node's world transform into a clone of its geometry and make sure a
// color attribute exists — the plant materials are vertexColors:true, and a
// missing attribute would render black. All-white = "no AO information".
function _glbBakedGeo(mesh) {
  const geo = mesh.geometry.clone();
  mesh.updateWorldMatrix(true, false);
  geo.applyMatrix4(mesh.matrixWorld);
  if (!geo.getAttribute('color')) {
    const n = geo.getAttribute('position').count;
    const col = new Float32Array(n * 3).fill(1);
    geo.setAttribute('color', new THREE.BufferAttribute(col, 3));
  }
  return geo;
}

// Extract named part meshes under `root` into {partName: BufferGeometry},
// re-normalised as one unit (same frame as the procedural archetypes: base
// y=0, height 1, scaled uniformly so the asset's authored aspect survives —
// normalizeUnit from 03-herbs.js, which stamps the measured half-width on each
// geometry for instancing to divide by). Blender object names are unique per
// file, so parts inside a tier/variant node are prefixed ('tier0_bark',
// 'v1_foliage'); bare names cover flat assets.
function _glbParts(root, partNames, prefix) {
  const out = {};
  for (const name of partNames) {
    const node = root.getObjectByName(name)
      || (prefix && root.getObjectByName(prefix + '_' + name));
    if (!node) continue;
    const geos = [];
    node.traverse((o) => { if (o.isMesh && o.geometry) geos.push(_glbBakedGeo(o)); });
    if (!geos.length) continue;
    out[name] = geos.length === 1 ? geos[0] : mergeGeometries(geos, false);
  }
  const all = Object.values(out);
  if (!all.length) return null;
  normalizeUnit(all);
  return out;
}

function _glbLoadPlant(loader, key, spec) {
  return loader.loadAsync('./assets/models/' + spec.file).then((gltf) => {
    const scn = gltf.scene;
    scn.updateMatrixWorld(true);
    const parts = spec.parts || ['foliage'];
    if (Array.isArray(spec.tiers) && spec.tiers.length) {
      const tiers = {};
      for (const t of spec.tiers) {
        const node = scn.getObjectByName('tier' + t);
        const p = node && _glbParts(node, parts, 'tier' + t);
        if (p && p.foliage) tiers[t] = p;
      }
      if (!Object.keys(tiers).length) throw new Error('no tier nodes');
      MODEL_PLANTS.set(key, { tiers });
    } else if (spec.variants || spec.variant_keys) {
      // Herb/shrub variants are one unit per (blade class, grain class) the
      // catalogue uses, so the whole parts bag is kept — a shrub variant carries
      // its own canes, and dropping them left a bare winter shrub invisible.
      const n = spec.variants || Object.keys(spec.variant_keys).length;
      const variants = [];
      for (let v = 0; v < n; v++) {
        const node = scn.getObjectByName('v' + v);
        const p = node && _glbParts(node, parts, 'v' + v);
        if (p && p.foliage) variants.push(p);
      }
      if (!variants.length) throw new Error('no variant nodes');
      MODEL_PLANTS.set(key, { variants, variantKeys: spec.variant_keys || null });
    } else {
      const p = _glbParts(scn, parts, '');
      if (!p || !p.foliage) throw new Error('no named parts');
      MODEL_PLANTS.set(key, { parts: p });
    }
  });
}

function _glbLoadFauna(loader, key, spec) {
  return loader.loadAsync('./assets/models/' + spec.file).then((gltf) => {
    gltf.scene.updateMatrixWorld(true);
    MODEL_FAUNA.set(key, { template: gltf.scene, spec });
  });
}

// Structures keep their authored GLB materials (fixed real-world colours —
// wood/stone/water; nothing seasonal), so the template is stored whole and
// cloned per placement.
function _glbLoadStruct(loader, key, spec) {
  return loader.loadAsync('./assets/models/' + spec.file).then((gltf) => {
    gltf.scene.updateMatrixWorld(true);
    MODEL_STRUCTS.set(key, { template: gltf.scene, spec });
  });
}

// Fire-and-forget boot load (the Spark idiom from 01-core.js): the first
// render never waits on models. When everything settles and at least one
// asset loaded, drop the archetype caches and re-push the last scene — the
// exact permaSetQuality idiom, so the camera stays put.
(function () {
  fetch('./assets/models/manifest.json')
    .then((r) => { if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })
    .then((mf) => {
      if (!mf || mf.version !== 1) throw new Error('unknown manifest version');
      const loader = new window.GLTFLoader();
      const jobs = [];
      for (const [key, spec] of Object.entries(mf.plants || {}))
        jobs.push(_glbLoadPlant(loader, key, spec)
          .catch((e) => console.info('[models] plant ' + key + ' skipped: ' + e.message)));
      for (const [key, spec] of Object.entries(mf.fauna || {}))
        jobs.push(_glbLoadFauna(loader, key, spec)
          .catch((e) => console.info('[models] fauna ' + key + ' skipped: ' + e.message)));
      for (const [key, spec] of Object.entries(mf.structures || {}))
        jobs.push(_glbLoadStruct(loader, key, spec)
          .catch((e) => console.info('[models] structure ' + key + ' skipped: ' + e.message)));
      return Promise.allSettled(jobs);
    })
    .then(() => {
      if (!MODEL_PLANTS.size && !MODEL_FAUNA.size && !MODEL_STRUCTS.size)
        throw new Error('nothing loaded');
      MODEL_STATE = 'ready';
      MODEL_COUNTS = { plants: MODEL_PLANTS.size, fauna: MODEL_FAUNA.size,
                       structs: MODEL_STRUCTS.size };
      console.info('[models] GLB assets active: ' + MODEL_COUNTS.plants
        + ' plant archetypes, ' + MODEL_COUNTS.fauna + ' fauna kinds, '
        + MODEL_COUNTS.structs + ' structures');
      // Rebuild with models (permaSetQuality idiom — camera stays put).
      TREE_CACHE.clear(); SHRUB_CACHE.clear(); HERB_CACHE.clear(); ARCH = null;
      if (lastSceneObj) window.permaSetScene(lastSceneObj);
      if (typeof WILDLIFE !== 'undefined' && WILDLIFE.length) rebuildWildlife();
    })
    .catch((e) => {
      MODEL_STATE = 'absent';
      console.info('[models] no GLB assets (' + e.message + ') — procedural geometry only');
    });
})();

// ── plant lookups (called from 04-quality.js, GLB-first with fallback) ──────

// One extra shared material: GLB bark carries baked-AO vertex colors, so it
// needs a vertexColors variant of MATS.branch. Living inside MATS keeps it
// protected by disposeDesignGroup's shared-material set automatically.
function _ensureModelMats() {
  ensurePlantMats();
}

// Tree archetype for (crown class, conifer kind, genus profile, form, tier).
// Key mapping mirrors the manifest: conifers by kind (standard → the generic
// def_conifer), deciduous by genus profile id with the form-shaped defaults
// (def_slender/def_oval/def_spreading) as the fallback for unknown genera.
function glbTreeArch(cls, ck, profId, form, tier) {
  if (MODEL_STATE !== 'ready') return null;
  let key;
  if (cls === 'conifer') {
    key = 'tree.' + (ck === 'standard' ? 'def_conifer' : ck);
  } else {
    key = 'tree.' + profId;
    if (!MODEL_PLANTS.has(key)) key = 'tree.def_' + form;
  }
  const rec = MODEL_PLANTS.get(key);
  const t = rec && rec.tiers && (rec.tiers[tier] || rec.tiers[2]);
  if (!t || !t.bark || !t.foliage) return null;
  _ensureModelMats();
  // `vertexColorBark` rather than a material: since F63 the bark material also
  // depends on the species' bark class, so the caller picks it — but only the
  // loader knows these parts carry COLOR_0, which the procedural bark does not.
  return { branchGeo: t.bark, foliageGeo: t.foliage, vertexColorBark: true };
}

// The parts bag for one (form, variant key) unit, or the neutral 'broad_1' unit
// the generator always emits. Shared by the herb and shrub lookups: both files
// hold one unit per (blade class, grain class) the catalogue actually uses, so a
// key the manifest doesn't carry means the two classifiers have drifted apart
// (02-plants.js variantKeyFor ↔ assetlib/conventions.py) — degrade to neutral
// rather than dropping the plant.
function _glbVariant(key, vkey) {
  const rec = MODEL_PLANTS.get(key);
  if (!rec || !rec.variants || !rec.variants.length) return null;
  const map = rec.variantKeys;
  let i = map && vkey != null && map[vkey] != null ? map[vkey]
        : (map ? map.broad_1 : null);
  if (i == null) i = 0;
  return rec.variants[i % rec.variants.length] || null;
}

function glbShrubArch(form, vkey) {
  if (MODEL_STATE !== 'ready') return null;
  const p = _glbVariant('shrub.' + form, vkey);
  if (!p || !p.bark || !p.foliage) return null;
  _ensureModelMats();
  return { foliageGeo: p.foliage, stemGeo: p.bark, vertexColorBark: true };
}

function glbHerbArch(formName, vkey) {
  if (MODEL_STATE !== 'ready') return null;
  const p = _glbVariant('herb.' + formName, vkey);
  return (p && p.foliage) || null;
}

function glbLayerArch(kind, v) {
  if (MODEL_STATE !== 'ready') return null;
  const rec = MODEL_PLANTS.get('layer.' + kind);
  if (!rec || !rec.variants || !rec.variants.length) return null;
  const p = rec.variants[v % rec.variants.length];
  return (p && p.foliage) || null;
}

// How many units a layer archetype actually ships. Groundcover is variant-keyed
// like herbs and shrubs (one unit per blade × grain its 32 species use), so the
// count is not the hard-coded 2 the viewer used to assume — asking the manifest
// is what lets a species pick the mat with ITS leaf on it.
function glbLayerCount(kind) {
  if (MODEL_STATE !== 'ready') return 0;
  const rec = MODEL_PLANTS.get('layer.' + kind);
  return (rec && rec.variants && rec.variants.length) || 0;
}

// Manifest index of a layer unit by variant key ('trifoliate' → 'broad_2'…),
// or null when this layer is not variant-keyed (grass/aquatic/vine).
function glbLayerVariantIndex(kind, vkey) {
  if (MODEL_STATE !== 'ready') return null;
  const rec = MODEL_PLANTS.get('layer.' + kind);
  const map = rec && rec.variantKeys;
  if (!map) return null;
  const i = vkey != null && map[vkey] != null ? map[vkey] : map.broad_1;
  return i == null ? null : i;
}
window.glbLayerCount = glbLayerCount;
window.glbLayerVariantIndex = glbLayerVariantIndex;

// ── fauna (called from 07-wildlife.js rebuildWildlife, GLB-first) ───────────

// Per-kind animation + scale constants, copied from the procedural critter
// factories so a GLB critter moves exactly like its procedural sibling
// (makeBeeAvatar/makeButterflyAvatar in 06-fly.js; makeBirdCritter etc. in
// 07-wildlife.js). Scale formulas match each factory's final setScalar.
const _GLB_CRITTER = {
  // `node` picks the BUILD inside a multi-variant file (V2.33, F67) — the
  // mechanism the fly's hover/darner pair established. A build the file does
  // not carry falls back to the first, which is the honest degradation: the
  // creature still flies, in the wrong silhouette, rather than vanishing.
  bee:       { key: 'bee', anim: 'flier',
               node: (a) => a.build || a.shape || 'stout',
               flap: { base: 0.2, amp: 0.75, speed: 0.09 },
               scale: (a) => 0.2 * (0.82 + 0.32 * (a.size || 1)) * 0.85 },
  // `skew` mirrors the procedural avatars in 06-fly.js — a slow lift and a
  // quick downstroke. The two flap tables have to agree or the baked and
  // procedural butterflies beat differently in the same scene.
  butterfly: { key: 'lep', anim: 'flier',
               node: (a) => a.build || 'butterfly',
               flap: { base: -1.05, amp: 2.20, speed: 0.028, skew: 0.64 },
               scale: () => 0.46 * 1.15 },
  moth:      { key: 'lep', anim: 'flier',
               node: (a) => a.build || 'moth',
               flap: { base: -0.75, amp: 1.55, speed: 0.055, skew: 0.58 },
               scale: () => 0.42 * 1.15 },
  // `node` was MISSING here until V2.45, and it is why birds never flapped.
  //
  // Without it `root` stayed the whole multi-variant file rather than one
  // build, so (a) every bird was drawn as passerine + woodpecker + hummer
  // superimposed, and (b) `prefix` below stayed empty — so `byName('WingL')`
  // looked for a bare `WingL` in a file whose nodes are `passerine_WingL`,
  // found nothing, and left `userData.wings` unset. `flapWings` returns early
  // without it, so the baked bird could not move its wings no matter what
  // frequency it was given. The procedural fallback set wings correctly, which
  // is why this only showed up once the GLBs were loading.
  //
  // The build names match src/scene_wildlife._BIRD_BUILD_WORDS exactly
  // (woodpecker / hummer / passerine); `tests/test_flight_model.py` now fails
  // if a multi-variant fauna GLB has a spec with no `node`.
  bird:      { key: 'bird',
               node: (a) => a.hummer ? 'hummer' : (a.build || 'passerine'),
               anim: (a) => a.hummer ? 'hover' : 'perch',
               // Matches the procedural bird in 07-wildlife.js — a slow deep
               // beat, folded on the perch by animateWildlife's gain. Was
               // amp 0.0 here too, so the baked bird was as motionless as the
               // procedural one.
               // V2.45b: a songbird's downstroke goes well below horizontal
               // and the recovery well above it; 0.9 rad centred near flat
               // was a shrug, not a wingbeat.
               flap: (a) => a.hummer ? { base: 0, amp: 1.1, speed: 0.4 }
                                     : { base: -0.55, amp: 1.7, speed: 0.22 },
               scale: (a) => 0.9 * (a.size || 1) },
  fly:       { key: 'fly', node: (a) => a.elongate ? 'darner' : 'hover',
               anim: (a) => a.elongate ? 'hover' : 'flier',
               flap: (a) => a.elongate ? { base: 0, amp: 0.25, speed: 0.3 }
                                       : { base: 0.1, amp: 0.8, speed: 0.5 },
               scale: (a) => 0.9 * (a.size || 1) },
  beetle:    { key: 'beetle', anim: 'crawl', flap: null,
               scale: (a) => 1.1 * (a.size || 1) },
  bat:       { key: 'bat', anim: 'flier',
               flap: { base: 0, amp: 0.9, speed: 0.28 },
               scale: (a) => 1.1 * (a.size || 1) },
  mammal:    { key: 'mammal', anim: 'ground', flap: null,
               scale: (a) => 1.0 * (a.size || 1) },
};

// GLB material names → the SAME material factories the procedural critters
// use (_cmat/_wingMat from 07-wildlife.js), tinted from the appearance bag.
// Defaults mirror the procedural builders so a missing field looks identical.
function _glbFaunaMat(name, app, kind) {
  const met = { flat: true, metal: !!app.metallic };
  const moth = kind === 'moth';
  const lep = (hex, fb) => (hex ? new THREE.Color(hex).getHex() : fb);
  switch (name) {
    case 'MatFuzz': return _cmat(app.fuzz || '#d99b26', met);
    case 'MatDark': return _cmat(app.dark || '#201a14', met);
    case 'MatWing':
      // Bird wings/tail are solid feather colour (procedural uses _cmat);
      // insect wings are the translucent membrane material.
      return kind === 'bird' ? _cmat(app.wing || '#6b7686', { flat: true })
                             : _wingMat(app.wing);
    case 'MatBody': return _cmat(app.body || '#5b6675',
      { flat: true, metal: kind === 'beetle' || (kind === 'fly' && !app.elongate) });
    case 'MatBelly': return _cmat(app.belly || '#e8e2d4', { flat: true });
    case 'MatFur': return _cmat(app.body || '#3a2f28', { flat: true });
    case 'MatFore': case 'MatHind': {
      const c = name === 'MatFore' ? lep(app.fore, moth ? 0xb8a274 : 0xe6912f)
                                   : lep(app.hind, moth ? 0x9c8763 : 0xd8701f);
      return new THREE.MeshStandardMaterial({ color: c, roughness: 0.7,
        emissive: c, emissiveIntensity: 0.28, side: THREE.DoubleSide,
        flatShading: true });
    }
    case 'MatEdge': return new THREE.MeshBasicMaterial({
      color: lep(app.edge, moth ? 0x5c4a30 : 0x2a1c10), side: THREE.DoubleSide,
      transparent: true, opacity: 0.5 });
    case 'MatMembrane': return new THREE.MeshStandardMaterial({
      color: 0x2a2430, roughness: 0.9, emissive: 0x0e0b12,
      emissiveIntensity: 0.5, side: THREE.DoubleSide, flatShading: true });
    default: return _cmat(app.body || '#6b6b62', { flat: true });
  }
}

// Build one critter from its GLB template: deep-clone (cloning geometry too,
// so disposeWildlife's per-critter geometry.dispose() stays correct), swap
// every material for a viewer-built one keyed by the GLB material's name,
// apply the appearance toggles, and wire the named wing nodes into the
// userData.wings/flap/anim contract animateWildlife + flapWings expect.
function glbCritter(kind, app) {
  if (MODEL_STATE !== 'ready') return null;
  app = app || {};
  const spec = _GLB_CRITTER[kind === 'mammal' && app.form === 'bat' ? 'bat' : kind];
  if (!spec) return null;
  const rec = MODEL_FAUNA.get(spec.key);
  if (!rec) return null;
  let root = rec.template;
  if (spec.node) {
    const want = spec.node(app);
    root = root.getObjectByName(want)
      // A build this file doesn't carry means the appearance layer and the
      // generator's variant list have drifted (src/scene_wildlife.py ↔
      // assetlib/fauna_variants.py). Degrade to the first build rather than
      // dropping the creature out of the scene entirely.
      || ((rec.spec && rec.spec.nodes && rec.spec.nodes.length)
          ? root.getObjectByName(rec.spec.nodes[0]) : null);
    if (!root) return null;
  }
  const g = root.clone(true);
  g.position.set(0, 0, 0);
  g.traverse((o) => {
    if (!o.isMesh) return;
    o.geometry = o.geometry.clone();
    const mname = (o.material && o.material.name) || '';
    o.material = _glbFaunaMat(mname, app, kind);
  });
  // Node names inside a multi-variant file are prefixed with the variant
  // root's name ('hover_WingL') — Blender object names are unique per file.
  const prefix = spec.node ? root.name + '_' : '';
  const byName = (n) => g.getObjectByName(n) || (prefix && g.getObjectByName(prefix + n));
  // Appearance toggles by node name.
  const nb = Math.max(0, Math.min(3, app.bands | 0));
  for (let i = 0; i < 3; i++) {
    const band = byName('Band' + i);
    if (band) band.visible = i < nb;
  }
  const spots = byName('Spots');
  if (spots) spots.visible = !!app.spots;
  const beak = byName('Beak');
  if (beak && app.hummer) beak.scale.z *= 2.4;
  // Bee body form: the GLB abdomen is authored 'round'; slender/stout are
  // relative rescales (ratios from makeBeeAvatar's shape table, 06-fly.js).
  const abd = byName('Abdomen');
  if (abd && kind === 'bee' && app.shape && app.shape !== 'round') {
    const r = app.shape === 'slender' ? [0.89, 0.91, 1.17] : [1.11, 1.08, 0.83];
    abd.scale.set(abd.scale.x * r[0], abd.scale.y * r[1], abd.scale.z * r[2]);
  }
  // Wing pivots: wrap each wing node in a fresh Group at its position, so
  // flapWings' pivot.rotation.z drives a clean roll in the critter's frame
  // regardless of any rotation the exporter baked onto the node itself.
  // Front pair only — a rear (dragonfly) pair stays static, matching the
  // procedural darner.
  const wings = [];
  for (const [n, sign] of [['WingL', -1], ['WingR', 1]]) {
    const node = byName(n);
    if (!node || !node.parent) continue;
    const pivot = new THREE.Group();
    pivot.position.copy(node.position);
    pivot.quaternion.copy(node.quaternion);
    node.parent.add(pivot);
    node.position.set(0, 0, 0);
    node.quaternion.identity();
    pivot.add(node);
    // LEPIDOPTERA: WingL/WingR are EMPTY grouping nodes, and the wing geometry
    // is their SIBLINGS — ForeL/HindL/RimL per side (V2.45b). Birds, bees and
    // flies carry the mesh on WingL/WingR itself, so this loop finds nothing
    // extra for them and costs nothing.
    //
    // This is why butterflies were reported "horizontal and flat and just
    // glide along": the pivot was rotating an empty node at the correct rate
    // while the six meshes that are actually the wings sat untouched in their
    // authored pose. It matched the procedural avatar's own structure all
    // along — 06-fly.js does `pivot.add(fore, hind, rim)` — which is exactly
    // why the fallback butterfly flapped and the baked one did not.
    const side = n.slice(-1);                     // 'L' | 'R'
    for (const part of ['Fore', 'Hind', 'Rim']) {
      const m = byName(part + side);
      if (!m || m === node) continue;
      // three.js `add` does not preserve world transform, and a pivot with a
      // non-zero offset would otherwise shift the part it adopts. Zero for the
      // leps, but the compensation keeps this correct for any future model.
      m.position.sub(pivot.position);
      pivot.add(m);
    }
    wings.push({ pivot, sign });
  }
  if (wings.length) g.userData.wings = wings;
  const flap = typeof spec.flap === 'function' ? spec.flap(app) : spec.flap;
  if (flap) g.userData.flap = flap;
  g.userData.anim = typeof spec.anim === 'function' ? spec.anim(app) : spec.anim;
  g.scale.setScalar(spec.scale(app));
  return g;
}

// ── structures (called from 05-flowers.js buildStructures, GLB-first) ───────

// One placed structure as a clone of its GLB template — geometry AND
// materials cloned so disposeDesignGroup's per-rebuild dispose stays correct.
// Scaled uniformly in XZ by the placement's size_m over the authored size;
// 'footprint' assets (ponds, lawns, fences) keep their authored height,
// 'uniform' objects scale with it. `s` is the scene structure record.
function glbStructure(s) {
  if (MODEL_STATE !== 'ready' || !s || !s.struct_id) return null;
  const rec = MODEL_STRUCTS.get(s.struct_id);
  if (!rec) return null;
  const g = rec.template.clone(true);
  g.traverse((o) => {
    if (!o.isMesh) return;
    o.geometry = o.geometry.clone();
    o.material = o.material.clone();
    o.castShadow = o.receiveShadow = true;
  });
  const sxz = Math.max(0.05, (s.size_m || rec.spec.size_m) / rec.spec.size_m);
  const sy = rec.spec.scale_mode === 'footprint' ? 1 : sxz;
  g.scale.set(sxz, sy, sxz);
  return g;
}
