// Part of the Site & Pattern 3D viewer, split out of the former
// single html/scene3d.html <script> (V2.24). Loaded as an ordered
// CLASSIC script by the bootstrap in scene3d.html — it shares the
// global scope with its siblings (THREE/OrbitControls/mergeGeometries
// are globals set by the bootstrap), so load ORDER is dependency
// order. Do not add ES `import`/`export` here.

// ── Blender-authored GLB model assets (V2.27) ───────────────────────────────
// Loads the low-poly GLB archetypes generated by scripts/blender/assetlib
// (committed under html/assets/models/) and serves them to the plant and
// wildlife builders through the window.glb* lookups below. The procedural
// geometry in chunks 02–04/07 is the PERMANENT fallback, not a transition:
// every lookup returns null until (and unless) the manifest and its files
// load, and any per-file failure just leaves that archetype procedural.
// Contract with the generator (see docs/3D_ASSETS.md):
//   · plants: unit frame (base y=0, height 1) — re-normalised here with the
//     same normalizeUnit() the procedural builders use; mesh parts named
//     'bark' / 'foliage'; COLOR_0 is grayscale AO so the per-instance
//     seasonal/health/presence tints multiply through unchanged.
//   · imported materials are DISCARDED — geometry marries the viewer's own
//     plantMaterial instances (wind sway, vertexColors, shared in MATS).
//   · fauna: one template per kind with named nodes (WingL/WingR pivots at
//     the hinge, Band0..2, Spots, Beak…) and named materials (MatFuzz,
//     MatBody…) that map onto the existing per-species appearance bags.
// This chunk registers NO window.perma* hooks (the bridge contract in
// tests/test_bridge_contract.py pins viewer hooks to map3d_js builders).

let MODEL_STATE = 'loading';        // 'loading' | 'ready' | 'absent'
const MODEL_PLANTS = new Map();     // manifest key → {tiers:{n:{bark,foliage}}} | {parts} | {variants:[geo]}
const MODEL_FAUNA = new Map();      // fauna key → {template, spec}
let MODEL_COUNTS = null;            // {plants, fauna} once ready (for the log line)

// Every GLB master geometry, so disposeDesignGroup can protect them the same
// way it protects the procedural archetype caches (a quality change clears
// those caches, and without this the masters inside the old design group
// would be disposed and the next rebuild would instance dead geometry).
window.glbSharedGeos = function () {
  const out = [];
  for (const rec of MODEL_PLANTS.values()) {
    if (rec.tiers) for (const t of Object.values(rec.tiers)) {
      if (t.bark) out.push(t.bark);
      if (t.foliage) out.push(t.foliage);
    }
    if (rec.variants) for (const g of rec.variants) out.push(g);
    if (rec.parts) {
      if (rec.parts.bark) out.push(rec.parts.bark);
      if (rec.parts.foliage) out.push(rec.parts.foliage);
    }
  }
  return out;
};

// ── loading ─────────────────────────────────────────────────────────────────

// Bake a node's world transform into a clone of its geometry and make sure a
// color attribute exists — the plant materials are vertexColors:true, and a
// missing attribute would render black. All-white = "no AO information".
function _glbBakedGeo(mesh) {
  const geo = mesh.geometry.clone();
  mesh.updateWorldMatrix(true, false);
  geo.applyMatrix4(mesh.matrixWorld);
  if (!geo.getAttribute('color')) {
    const n = geo.getAttribute('position').count;
    const col = new Float32Array(n * 3).fill(1);
    geo.setAttribute('color', new THREE.BufferAttribute(col, 3));
  }
  return geo;
}

// Extract named part meshes under `root` into {partName: BufferGeometry},
// re-normalised as one unit (same frame as the procedural archetypes: base
// y=0, height 1, half-width 0.5 — normalizeUnit from 03-herbs.js). Blender
// object names are unique per file, so parts inside a tier/variant node are
// prefixed ('tier0_bark', 'v1_foliage'); bare names cover flat assets.
function _glbParts(root, partNames, prefix) {
  const out = {};
  for (const name of partNames) {
    const node = root.getObjectByName(name)
      || (prefix && root.getObjectByName(prefix + '_' + name));
    if (!node) continue;
    const geos = [];
    node.traverse((o) => { if (o.isMesh && o.geometry) geos.push(_glbBakedGeo(o)); });
    if (!geos.length) continue;
    out[name] = geos.length === 1 ? geos[0] : mergeGeometries(geos, false);
  }
  const all = Object.values(out);
  if (!all.length) return null;
  normalizeUnit(all);
  return out;
}

function _glbLoadPlant(loader, key, spec) {
  return loader.loadAsync('./assets/models/' + spec.file).then((gltf) => {
    const scn = gltf.scene;
    scn.updateMatrixWorld(true);
    const parts = spec.parts || ['foliage'];
    if (Array.isArray(spec.tiers) && spec.tiers.length) {
      const tiers = {};
      for (const t of spec.tiers) {
        const node = scn.getObjectByName('tier' + t);
        const p = node && _glbParts(node, parts, 'tier' + t);
        if (p && p.foliage) tiers[t] = p;
      }
      if (!Object.keys(tiers).length) throw new Error('no tier nodes');
      MODEL_PLANTS.set(key, { tiers });
    } else if (spec.variants) {
      const variants = [];
      for (let v = 0; v < spec.variants; v++) {
        const node = scn.getObjectByName('v' + v);
        const p = node && _glbParts(node, parts, 'v' + v);
        if (p && p.foliage) variants.push(p.foliage);
      }
      if (!variants.length) throw new Error('no variant nodes');
      MODEL_PLANTS.set(key, { variants });
    } else {
      const p = _glbParts(scn, parts, '');
      if (!p || !p.foliage) throw new Error('no named parts');
      MODEL_PLANTS.set(key, { parts: p });
    }
  });
}

function _glbLoadFauna(loader, key, spec) {
  return loader.loadAsync('./assets/models/' + spec.file).then((gltf) => {
    gltf.scene.updateMatrixWorld(true);
    MODEL_FAUNA.set(key, { template: gltf.scene, spec });
  });
}

// Fire-and-forget boot load (the Spark idiom from 01-core.js): the first
// render never waits on models. When everything settles and at least one
// asset loaded, drop the archetype caches and re-push the last scene — the
// exact permaSetQuality idiom, so the camera stays put.
(function () {
  fetch('./assets/models/manifest.json')
    .then((r) => { if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })
    .then((mf) => {
      if (!mf || mf.version !== 1) throw new Error('unknown manifest version');
      const loader = new window.GLTFLoader();
      const jobs = [];
      for (const [key, spec] of Object.entries(mf.plants || {}))
        jobs.push(_glbLoadPlant(loader, key, spec)
          .catch((e) => console.info('[models] plant ' + key + ' skipped: ' + e.message)));
      for (const [key, spec] of Object.entries(mf.fauna || {}))
        jobs.push(_glbLoadFauna(loader, key, spec)
          .catch((e) => console.info('[models] fauna ' + key + ' skipped: ' + e.message)));
      return Promise.allSettled(jobs);
    })
    .then(() => {
      if (!MODEL_PLANTS.size && !MODEL_FAUNA.size) throw new Error('nothing loaded');
      MODEL_STATE = 'ready';
      MODEL_COUNTS = { plants: MODEL_PLANTS.size, fauna: MODEL_FAUNA.size };
      console.info('[models] GLB assets active: ' + MODEL_COUNTS.plants
        + ' plant archetypes, ' + MODEL_COUNTS.fauna + ' fauna kinds');
      // Rebuild with models (permaSetQuality idiom — camera stays put).
      TREE_CACHE.clear(); SHRUB_CACHE.clear(); HERB_CACHE.clear(); ARCH = null;
      if (lastSceneObj) window.permaSetScene(lastSceneObj);
      if (typeof WILDLIFE !== 'undefined' && WILDLIFE.length) rebuildWildlife();
    })
    .catch((e) => {
      MODEL_STATE = 'absent';
      console.info('[models] no GLB assets (' + e.message + ') — procedural geometry only');
    });
})();

// ── plant lookups (called from 04-quality.js, GLB-first with fallback) ──────

// One extra shared material: GLB bark carries baked-AO vertex colors, so it
// needs a vertexColors variant of MATS.branch. Living inside MATS keeps it
// protected by disposeDesignGroup's shared-material set automatically.
function _ensureModelMats() {
  ensurePlantMats();
  if (!MATS.glbBark)
    MATS.glbBark = plantMaterial({ roughness: 0.92, wind: 0.015, vertexColors: true });
}

// Tree archetype for (crown class, conifer kind, genus profile, form, tier).
// Key mapping mirrors the manifest: conifers by kind (standard → the generic
// def_conifer), deciduous by genus profile id with the form-shaped defaults
// (def_slender/def_oval/def_spreading) as the fallback for unknown genera.
function glbTreeArch(cls, ck, profId, form, tier) {
  if (MODEL_STATE !== 'ready') return null;
  let key;
  if (cls === 'conifer') {
    key = 'tree.' + (ck === 'standard' ? 'def_conifer' : ck);
  } else {
    key = 'tree.' + profId;
    if (!MODEL_PLANTS.has(key)) key = 'tree.def_' + form;
  }
  const rec = MODEL_PLANTS.get(key);
  const t = rec && rec.tiers && (rec.tiers[tier] || rec.tiers[2]);
  if (!t || !t.bark || !t.foliage) return null;
  _ensureModelMats();
  return { branchGeo: t.bark, foliageGeo: t.foliage, branchMat: MATS.glbBark };
}

function glbShrubArch(form) {
  if (MODEL_STATE !== 'ready') return null;
  const rec = MODEL_PLANTS.get('shrub.' + form);
  const p = rec && rec.parts;
  if (!p || !p.bark || !p.foliage) return null;
  _ensureModelMats();
  return { foliageGeo: p.foliage, stemGeo: p.bark, stemMat: MATS.glbBark };
}

function glbHerbArch(formName) {
  if (MODEL_STATE !== 'ready') return null;
  const rec = MODEL_PLANTS.get('herb.' + formName);
  return (rec && rec.parts && rec.parts.foliage) || null;
}

function glbLayerArch(kind, v) {
  if (MODEL_STATE !== 'ready') return null;
  const rec = MODEL_PLANTS.get('layer.' + kind);
  if (!rec || !rec.variants || !rec.variants.length) return null;
  return rec.variants[v % rec.variants.length];
}

// ── fauna (called from 07-wildlife.js rebuildWildlife, GLB-first) ───────────

// Per-kind animation + scale constants, copied from the procedural critter
// factories so a GLB critter moves exactly like its procedural sibling
// (makeBeeAvatar/makeButterflyAvatar in 06-fly.js; makeBirdCritter etc. in
// 07-wildlife.js). Scale formulas match each factory's final setScalar.
const _GLB_CRITTER = {
  bee:       { key: 'bee', anim: 'flier',
               flap: { base: 0.2, amp: 0.75, speed: 0.09 },
               scale: (a) => 0.2 * (0.82 + 0.32 * (a.size || 1)) * 0.85 },
  butterfly: { key: 'lep', anim: 'flier',
               flap: { base: -0.6, amp: 1.05, speed: 0.028 },
               scale: () => 0.46 * 1.15 },
  moth:      { key: 'lep', anim: 'flier',
               flap: { base: -0.45, amp: 0.75, speed: 0.055 },
               scale: () => 0.42 * 1.15 },
  bird:      { key: 'bird', anim: (a) => a.hummer ? 'hover' : 'perch',
               flap: (a) => a.hummer ? { base: 0, amp: 1.1, speed: 0.4 }
                                     : { base: -0.2, amp: 0.0, speed: 0.05 },
               scale: (a) => 0.9 * (a.size || 1) },
  fly:       { key: 'fly', node: (a) => a.elongate ? 'darner' : 'hover',
               anim: (a) => a.elongate ? 'hover' : 'flier',
               flap: (a) => a.elongate ? { base: 0, amp: 0.25, speed: 0.3 }
                                       : { base: 0.1, amp: 0.8, speed: 0.5 },
               scale: (a) => 0.9 * (a.size || 1) },
  beetle:    { key: 'beetle', anim: 'crawl', flap: null,
               scale: (a) => 1.1 * (a.size || 1) },
  bat:       { key: 'bat', anim: 'flier',
               flap: { base: 0, amp: 0.9, speed: 0.28 },
               scale: (a) => 1.1 * (a.size || 1) },
  mammal:    { key: 'mammal', anim: 'ground', flap: null,
               scale: (a) => 1.0 * (a.size || 1) },
};

// GLB material names → the SAME material factories the procedural critters
// use (_cmat/_wingMat from 07-wildlife.js), tinted from the appearance bag.
// Defaults mirror the procedural builders so a missing field looks identical.
function _glbFaunaMat(name, app, kind) {
  const met = { flat: true, metal: !!app.metallic };
  const moth = kind === 'moth';
  const lep = (hex, fb) => (hex ? new THREE.Color(hex).getHex() : fb);
  switch (name) {
    case 'MatFuzz': return _cmat(app.fuzz || '#d99b26', met);
    case 'MatDark': return _cmat(app.dark || '#201a14', met);
    case 'MatWing': return _wingMat(app.wing);
    case 'MatBody': return _cmat(app.body || '#5b6675',
      { flat: true, metal: kind === 'beetle' || (kind === 'fly' && !app.elongate) });
    case 'MatBelly': return _cmat(app.belly || '#e8e2d4', { flat: true });
    case 'MatFur': return _cmat(app.body || '#3a2f28', { flat: true });
    case 'MatFore': case 'MatHind': {
      const c = name === 'MatFore' ? lep(app.fore, moth ? 0xb8a274 : 0xe6912f)
                                   : lep(app.hind, moth ? 0x9c8763 : 0xd8701f);
      return new THREE.MeshStandardMaterial({ color: c, roughness: 0.7,
        emissive: c, emissiveIntensity: 0.28, side: THREE.DoubleSide,
        flatShading: true });
    }
    case 'MatEdge': return new THREE.MeshBasicMaterial({
      color: lep(app.edge, moth ? 0x5c4a30 : 0x2a1c10), side: THREE.DoubleSide,
      transparent: true, opacity: 0.5 });
    case 'MatMembrane': return new THREE.MeshStandardMaterial({
      color: 0x2a2430, roughness: 0.9, emissive: 0x0e0b12,
      emissiveIntensity: 0.5, side: THREE.DoubleSide, flatShading: true });
    default: return _cmat(app.body || '#6b6b62', { flat: true });
  }
}

// Build one critter from its GLB template: deep-clone (cloning geometry too,
// so disposeWildlife's per-critter geometry.dispose() stays correct), swap
// every material for a viewer-built one keyed by the GLB material's name,
// apply the appearance toggles, and wire the named wing nodes into the
// userData.wings/flap/anim contract animateWildlife + flapWings expect.
function glbCritter(kind, app) {
  if (MODEL_STATE !== 'ready') return null;
  app = app || {};
  const spec = _GLB_CRITTER[kind === 'mammal' && app.form === 'bat' ? 'bat' : kind];
  if (!spec) return null;
  const rec = MODEL_FAUNA.get(spec.key);
  if (!rec) return null;
  let root = rec.template;
  if (spec.node) {
    root = root.getObjectByName(spec.node(app));
    if (!root) return null;
  }
  const g = root.clone(true);
  g.position.set(0, 0, 0);
  g.traverse((o) => {
    if (!o.isMesh) return;
    o.geometry = o.geometry.clone();
    const mname = (o.material && o.material.name) || '';
    o.material = _glbFaunaMat(mname, app, kind);
  });
  // Node names inside a multi-variant file are prefixed with the variant
  // root's name ('hover_WingL') — Blender object names are unique per file.
  const prefix = spec.node ? root.name + '_' : '';
  const byName = (n) => g.getObjectByName(n) || (prefix && g.getObjectByName(prefix + n));
  // Appearance toggles by node name.
  const nb = Math.max(0, Math.min(3, app.bands | 0));
  for (let i = 0; i < 3; i++) {
    const band = byName('Band' + i);
    if (band) band.visible = i < nb;
  }
  const spots = byName('Spots');
  if (spots) spots.visible = !!app.spots;
  const beak = byName('Beak');
  if (beak && app.hummer) beak.scale.z *= 2.4;
  // Wing pivots: wrap each wing node in a fresh Group at its position, so
  // flapWings' pivot.rotation.z drives a clean roll in the critter's frame
  // regardless of any rotation the exporter baked onto the node itself.
  // Front pair only — a rear (dragonfly) pair stays static, matching the
  // procedural darner.
  const wings = [];
  for (const [n, sign] of [['WingL', -1], ['WingR', 1]]) {
    const node = byName(n);
    if (!node || !node.parent) continue;
    const pivot = new THREE.Group();
    pivot.position.copy(node.position);
    pivot.quaternion.copy(node.quaternion);
    node.parent.add(pivot);
    node.position.set(0, 0, 0);
    node.quaternion.identity();
    pivot.add(node);
    wings.push({ pivot, sign });
  }
  if (wings.length) g.userData.wings = wings;
  const flap = typeof spec.flap === 'function' ? spec.flap(app) : spec.flap;
  if (flap) g.userData.flap = flap;
  g.userData.anim = typeof spec.anim === 'function' ? spec.anim(app) : spec.anim;
  g.scale.setScalar(spec.scale(app));
  return g;
}
