"""
calendar_data.py — Edmonton Zone 3b planting calendar seed data.

Climate assumptions (Edmonton, AB — Zone 3b):
  Last spring frost:  ~May 20
  First fall frost:   ~Sep 20
  Growing season:     ~122 days
  Indoor seed start:  Late February – April (species-dependent)

Status values:
  dormant        – plant is dormant / not active
  start_indoors  – start seeds indoors under lights
  direct_sow     – sow seeds directly outdoors
  transplant     – transplant seedlings / divisions outdoors
  growing        – active growth period
  harvest        – primary harvest window
  pruning        – best time for pruning

Each tuple: (common_name, month, status, notes)
"""

SEED_CALENDAR: list[tuple] = [

    # ═══════════════════════════════════════════════════════════════════════
    # TREES
    # ═══════════════════════════════════════════════════════════════════════

    # Trembling Aspen — native, no sowing; transplant bare-root in spring
    ("Trembling Aspen", 1,  "dormant",    None),
    ("Trembling Aspen", 2,  "dormant",    None),
    ("Trembling Aspen", 3,  "dormant",    None),
    ("Trembling Aspen", 4,  "dormant",    "Order bare-root stock"),
    ("Trembling Aspen", 5,  "transplant", "Plant bare-root trees after soil thaws"),
    ("Trembling Aspen", 6,  "growing",    "Water well during establishment"),
    ("Trembling Aspen", 7,  "growing",    None),
    ("Trembling Aspen", 8,  "growing",    None),
    ("Trembling Aspen", 9,  "growing",    "Fall colour begins"),
    ("Trembling Aspen", 10, "dormant",    "Leaf drop"),
    ("Trembling Aspen", 11, "dormant",    None),
    ("Trembling Aspen", 12, "dormant",    None),

    # White Spruce
    ("White Spruce", 1,  "dormant",    None),
    ("White Spruce", 2,  "dormant",    None),
    ("White Spruce", 3,  "dormant",    None),
    ("White Spruce", 4,  "dormant",    "Order nursery stock"),
    ("White Spruce", 5,  "transplant", "Plant balled-and-burlapped or container trees"),
    ("White Spruce", 6,  "growing",    "Water deeply weekly"),
    ("White Spruce", 7,  "growing",    None),
    ("White Spruce", 8,  "growing",    None),
    ("White Spruce", 9,  "growing",    None),
    ("White Spruce", 10, "dormant",    None),
    ("White Spruce", 11, "dormant",    None),
    ("White Spruce", 12, "dormant",    None),

    # Paper Birch
    ("Paper Birch", 1,  "dormant",    None),
    ("Paper Birch", 2,  "dormant",    None),
    ("Paper Birch", 3,  "dormant",    None),
    ("Paper Birch", 4,  "dormant",    "Sap run — can tap for birch water"),
    ("Paper Birch", 5,  "transplant", "Plant bare-root or container trees"),
    ("Paper Birch", 6,  "growing",    "Keep soil consistently moist"),
    ("Paper Birch", 7,  "growing",    None),
    ("Paper Birch", 8,  "growing",    None),
    ("Paper Birch", 9,  "growing",    "Fall colour begins"),
    ("Paper Birch", 10, "dormant",    None),
    ("Paper Birch", 11, "dormant",    None),
    ("Paper Birch", 12, "dormant",    None),

    # Goodland Apple
    ("Goodland Apple", 1,  "dormant",    None),
    ("Goodland Apple", 2,  "dormant",    None),
    ("Goodland Apple", 3,  "pruning",    "Prune before bud break while still dormant"),
    ("Goodland Apple", 4,  "dormant",    "Order bare-root trees; apply dormant oil"),
    ("Goodland Apple", 5,  "transplant", "Plant bare-root trees; blooms mid-May"),
    ("Goodland Apple", 6,  "growing",    "Thin fruitlets after June drop"),
    ("Goodland Apple", 7,  "growing",    "Water deeply every 7–10 days"),
    ("Goodland Apple", 8,  "harvest",    "Harvest ripe fruit mid–late August"),
    ("Goodland Apple", 9,  "harvest",    "Pick remaining fruit before frost"),
    ("Goodland Apple", 10, "dormant",    "Clean up fallen fruit; mulch roots"),
    ("Goodland Apple", 11, "dormant",    "Wrap trunk to prevent sunscald"),
    ("Goodland Apple", 12, "dormant",    None),

    # Norland Apple
    ("Norland Apple", 1,  "dormant",    None),
    ("Norland Apple", 2,  "dormant",    None),
    ("Norland Apple", 3,  "pruning",    "Prune before bud break"),
    ("Norland Apple", 4,  "dormant",    "Apply dormant oil spray"),
    ("Norland Apple", 5,  "transplant", "Plant bare-root trees; blooms mid-May"),
    ("Norland Apple", 6,  "growing",    "Thin fruitlets after June drop"),
    ("Norland Apple", 7,  "harvest",    "Very early — harvest late July"),
    ("Norland Apple", 8,  "harvest",    "Harvest early August"),
    ("Norland Apple", 9,  "growing",    "Post-harvest care; water until freeze"),
    ("Norland Apple", 10, "dormant",    "Clean up; mulch roots"),
    ("Norland Apple", 11, "dormant",    "Wrap trunk"),
    ("Norland Apple", 12, "dormant",    None),

    # Evans Cherry
    ("Evans Cherry", 1,  "dormant",    None),
    ("Evans Cherry", 2,  "dormant",    None),
    ("Evans Cherry", 3,  "pruning",    "Prune before bud break"),
    ("Evans Cherry", 4,  "dormant",    "Order nursery stock"),
    ("Evans Cherry", 5,  "transplant", "Plant; blooms in May"),
    ("Evans Cherry", 6,  "growing",    "Fruit developing; net to protect from birds"),
    ("Evans Cherry", 7,  "harvest",    "Harvest tart cherries mid–late July"),
    ("Evans Cherry", 8,  "harvest",    "Finish harvest early August"),
    ("Evans Cherry", 9,  "growing",    None),
    ("Evans Cherry", 10, "dormant",    "Mulch around base"),
    ("Evans Cherry", 11, "dormant",    None),
    ("Evans Cherry", 12, "dormant",    None),

    # Pembina Plum
    ("Pembina Plum", 1,  "dormant",    None),
    ("Pembina Plum", 2,  "dormant",    None),
    ("Pembina Plum", 3,  "pruning",    "Prune before bud break"),
    ("Pembina Plum", 4,  "dormant",    None),
    ("Pembina Plum", 5,  "transplant", "Plant; blooms May"),
    ("Pembina Plum", 6,  "growing",    "Thin fruitlets for larger plums"),
    ("Pembina Plum", 7,  "growing",    None),
    ("Pembina Plum", 8,  "harvest",    "Harvest large purple plums Aug–Sep"),
    ("Pembina Plum", 9,  "harvest",    "Finish harvest early September"),
    ("Pembina Plum", 10, "dormant",    None),
    ("Pembina Plum", 11, "dormant",    None),
    ("Pembina Plum", 12, "dormant",    None),

    # Brookgold Plum
    ("Brookgold Plum", 1,  "dormant",    None),
    ("Brookgold Plum", 2,  "dormant",    None),
    ("Brookgold Plum", 3,  "pruning",    "Prune before bud break"),
    ("Brookgold Plum", 4,  "dormant",    None),
    ("Brookgold Plum", 5,  "transplant", "Plant; blooms May"),
    ("Brookgold Plum", 6,  "growing",    None),
    ("Brookgold Plum", 7,  "growing",    None),
    ("Brookgold Plum", 8,  "harvest",    "Harvest yellow plums in August"),
    ("Brookgold Plum", 9,  "growing",    None),
    ("Brookgold Plum", 10, "dormant",    None),
    ("Brookgold Plum", 11, "dormant",    None),
    ("Brookgold Plum", 12, "dormant",    None),

    # Siberian Larch
    ("Siberian Larch", 1,  "dormant",    None),
    ("Siberian Larch", 2,  "dormant",    None),
    ("Siberian Larch", 3,  "dormant",    None),
    ("Siberian Larch", 4,  "dormant",    None),
    ("Siberian Larch", 5,  "transplant", "Plant bare-root or container stock"),
    ("Siberian Larch", 6,  "growing",    None),
    ("Siberian Larch", 7,  "growing",    None),
    ("Siberian Larch", 8,  "growing",    None),
    ("Siberian Larch", 9,  "growing",    "Stunning golden fall colour"),
    ("Siberian Larch", 10, "dormant",    "Needle drop (deciduous conifer)"),
    ("Siberian Larch", 11, "dormant",    None),
    ("Siberian Larch", 12, "dormant",    None),

    # Bur Oak
    ("Bur Oak", 1,  "dormant",    None),
    ("Bur Oak", 2,  "dormant",    None),
    ("Bur Oak", 3,  "dormant",    None),
    ("Bur Oak", 4,  "dormant",    "Stratify acorns for spring planting"),
    ("Bur Oak", 5,  "transplant", "Plant container stock; slow to establish"),
    ("Bur Oak", 6,  "growing",    "Water deeply weekly for first 2 years"),
    ("Bur Oak", 7,  "growing",    None),
    ("Bur Oak", 8,  "growing",    None),
    ("Bur Oak", 9,  "harvest",    "Collect acorns Sep–Oct for propagation"),
    ("Bur Oak", 10, "harvest",    "Acorn harvest continues"),
    ("Bur Oak", 11, "dormant",    None),
    ("Bur Oak", 12, "dormant",    None),

    # ═══════════════════════════════════════════════════════════════════════
    # SHRUBS
    # ═══════════════════════════════════════════════════════════════════════

    # Saskatoon Berry
    ("Saskatoon Berry", 1,  "dormant",    None),
    ("Saskatoon Berry", 2,  "dormant",    None),
    ("Saskatoon Berry", 3,  "pruning",    "Remove dead/crossing branches"),
    ("Saskatoon Berry", 4,  "dormant",    None),
    ("Saskatoon Berry", 5,  "transplant", "Plant; white blooms appear late May"),
    ("Saskatoon Berry", 6,  "growing",    "Fruit developing"),
    ("Saskatoon Berry", 7,  "harvest",    "Harvest ripe berries early–mid July"),
    ("Saskatoon Berry", 8,  "growing",    None),
    ("Saskatoon Berry", 9,  "growing",    None),
    ("Saskatoon Berry", 10, "dormant",    "Mulch roots before freeze"),
    ("Saskatoon Berry", 11, "dormant",    None),
    ("Saskatoon Berry", 12, "dormant",    None),

    # Chokecherry
    ("Chokecherry", 1,  "dormant",    None),
    ("Chokecherry", 2,  "dormant",    None),
    ("Chokecherry", 3,  "pruning",    "Remove dead wood; shape"),
    ("Chokecherry", 4,  "dormant",    None),
    ("Chokecherry", 5,  "transplant", "Plant; blooms May–June"),
    ("Chokecherry", 6,  "growing",    "Blooming; fruit developing"),
    ("Chokecherry", 7,  "growing",    None),
    ("Chokecherry", 8,  "harvest",    "Harvest dark fruit Aug–Sep for jelly"),
    ("Chokecherry", 9,  "harvest",    "Finish harvest"),
    ("Chokecherry", 10, "dormant",    None),
    ("Chokecherry", 11, "dormant",    None),
    ("Chokecherry", 12, "dormant",    None),

    # Buffalo Berry
    ("Buffalo Berry", 1,  "dormant",    None),
    ("Buffalo Berry", 2,  "dormant",    None),
    ("Buffalo Berry", 3,  "dormant",    None),
    ("Buffalo Berry", 4,  "dormant",    None),
    ("Buffalo Berry", 5,  "transplant", "Plant container stock"),
    ("Buffalo Berry", 6,  "growing",    "Blooming"),
    ("Buffalo Berry", 7,  "harvest",    "Harvest tart berries Jul–Aug"),
    ("Buffalo Berry", 8,  "harvest",    "Berries sweeten after first light frost"),
    ("Buffalo Berry", 9,  "growing",    None),
    ("Buffalo Berry", 10, "dormant",    None),
    ("Buffalo Berry", 11, "dormant",    None),
    ("Buffalo Berry", 12, "dormant",    None),

    # Prickly Rose
    ("Prickly Rose", 1,  "dormant",    None),
    ("Prickly Rose", 2,  "dormant",    None),
    ("Prickly Rose", 3,  "dormant",    None),
    ("Prickly Rose", 4,  "dormant",    None),
    ("Prickly Rose", 5,  "transplant", "Plant container stock"),
    ("Prickly Rose", 6,  "growing",    "Fragrant pink blooms begin"),
    ("Prickly Rose", 7,  "growing",    "Peak bloom"),
    ("Prickly Rose", 8,  "harvest",    "Rose hips forming — harvest Aug–Oct"),
    ("Prickly Rose", 9,  "harvest",    "Hips reddest after first frost"),
    ("Prickly Rose", 10, "harvest",    "Final hip harvest"),
    ("Prickly Rose", 11, "dormant",    None),
    ("Prickly Rose", 12, "dormant",    None),

    # Black Currant
    ("Black Currant", 1,  "dormant",    None),
    ("Black Currant", 2,  "dormant",    None),
    ("Black Currant", 3,  "pruning",    "Remove oldest 3-year canes"),
    ("Black Currant", 4,  "dormant",    None),
    ("Black Currant", 5,  "transplant", "Plant; blooms May"),
    ("Black Currant", 6,  "growing",    "Fruit developing; mulch well"),
    ("Black Currant", 7,  "harvest",    "Harvest ripe black currants Jul–Aug"),
    ("Black Currant", 8,  "harvest",    "Continue harvest"),
    ("Black Currant", 9,  "growing",    None),
    ("Black Currant", 10, "dormant",    None),
    ("Black Currant", 11, "dormant",    None),
    ("Black Currant", 12, "dormant",    None),

    # Red Currant
    ("Red Currant", 1,  "dormant",    None),
    ("Red Currant", 2,  "dormant",    None),
    ("Red Currant", 3,  "pruning",    "Remove oldest canes"),
    ("Red Currant", 4,  "dormant",    None),
    ("Red Currant", 5,  "transplant", "Plant; blooms Apr–May"),
    ("Red Currant", 6,  "growing",    "Fruit developing"),
    ("Red Currant", 7,  "harvest",    "Harvest tart red currants in July"),
    ("Red Currant", 8,  "growing",    None),
    ("Red Currant", 9,  "growing",    None),
    ("Red Currant", 10, "dormant",    None),
    ("Red Currant", 11, "dormant",    None),
    ("Red Currant", 12, "dormant",    None),

    # Gooseberry
    ("Gooseberry", 1,  "dormant",    None),
    ("Gooseberry", 2,  "dormant",    None),
    ("Gooseberry", 3,  "pruning",    "Remove oldest canes; open centre"),
    ("Gooseberry", 4,  "dormant",    None),
    ("Gooseberry", 5,  "transplant", "Plant; blooms Apr–May"),
    ("Gooseberry", 6,  "growing",    "Fruit developing"),
    ("Gooseberry", 7,  "harvest",    "Harvest berries Jul–Aug"),
    ("Gooseberry", 8,  "harvest",    "Continue harvest"),
    ("Gooseberry", 9,  "growing",    None),
    ("Gooseberry", 10, "dormant",    None),
    ("Gooseberry", 11, "dormant",    None),
    ("Gooseberry", 12, "dormant",    None),

    # Raspberry
    ("Raspberry", 1,  "dormant",    None),
    ("Raspberry", 2,  "dormant",    None),
    ("Raspberry", 3,  "pruning",    "Cut dead canes to ground; thin to 6/ft"),
    ("Raspberry", 4,  "dormant",    "Uncover mulched canes"),
    ("Raspberry", 5,  "transplant", "Plant new canes; existing leafing out"),
    ("Raspberry", 6,  "growing",    "Blooming; mulch heavily"),
    ("Raspberry", 7,  "harvest",    "Main harvest window Jul–Aug"),
    ("Raspberry", 8,  "harvest",    "Continue picking every 2–3 days"),
    ("Raspberry", 9,  "growing",    "Fall varieties may still produce"),
    ("Raspberry", 10, "dormant",    "Mulch canes for winter protection"),
    ("Raspberry", 11, "dormant",    None),
    ("Raspberry", 12, "dormant",    None),

    # Nanking Cherry
    ("Nanking Cherry", 1,  "dormant",    None),
    ("Nanking Cherry", 2,  "dormant",    None),
    ("Nanking Cherry", 3,  "pruning",    "Shape; remove dead wood"),
    ("Nanking Cherry", 4,  "dormant",    None),
    ("Nanking Cherry", 5,  "transplant", "Plant; beautiful pink-white blooms in May"),
    ("Nanking Cherry", 6,  "growing",    "Fruit developing"),
    ("Nanking Cherry", 7,  "harvest",    "Harvest small red cherries Jul–Aug"),
    ("Nanking Cherry", 8,  "harvest",    "Continue harvest"),
    ("Nanking Cherry", 9,  "growing",    None),
    ("Nanking Cherry", 10, "dormant",    None),
    ("Nanking Cherry", 11, "dormant",    None),
    ("Nanking Cherry", 12, "dormant",    None),

    # Potentilla (Shrubby)
    ("Potentilla (Shrubby)", 1,  "dormant",    None),
    ("Potentilla (Shrubby)", 2,  "dormant",    None),
    ("Potentilla (Shrubby)", 3,  "pruning",    "Cut back by 1/3 to rejuvenate"),
    ("Potentilla (Shrubby)", 4,  "dormant",    None),
    ("Potentilla (Shrubby)", 5,  "transplant", "Plant container stock"),
    ("Potentilla (Shrubby)", 6,  "growing",    "Blooming begins — lasts until frost"),
    ("Potentilla (Shrubby)", 7,  "growing",    "Continuous bloom"),
    ("Potentilla (Shrubby)", 8,  "growing",    "Continuous bloom"),
    ("Potentilla (Shrubby)", 9,  "growing",    "Still blooming until hard frost"),
    ("Potentilla (Shrubby)", 10, "dormant",    None),
    ("Potentilla (Shrubby)", 11, "dormant",    None),
    ("Potentilla (Shrubby)", 12, "dormant",    None),

    # Red Osier Dogwood
    ("Red Osier Dogwood", 1,  "dormant",    "Striking red stems visible"),
    ("Red Osier Dogwood", 2,  "dormant",    None),
    ("Red Osier Dogwood", 3,  "pruning",    "Cut 1/3 oldest stems to ground for colour"),
    ("Red Osier Dogwood", 4,  "dormant",    None),
    ("Red Osier Dogwood", 5,  "transplant", "Plant; blooms May–June"),
    ("Red Osier Dogwood", 6,  "growing",    "White flower clusters"),
    ("Red Osier Dogwood", 7,  "growing",    "White berries forming"),
    ("Red Osier Dogwood", 8,  "growing",    None),
    ("Red Osier Dogwood", 9,  "growing",    "Fall colour and berries for birds"),
    ("Red Osier Dogwood", 10, "dormant",    None),
    ("Red Osier Dogwood", 11, "dormant",    None),
    ("Red Osier Dogwood", 12, "dormant",    "Red stems brighten winter garden"),

    # Snowberry
    ("Snowberry", 1,  "dormant",    "White berries still visible on bare stems"),
    ("Snowberry", 2,  "dormant",    None),
    ("Snowberry", 3,  "pruning",    "Prune to shape if needed"),
    ("Snowberry", 4,  "dormant",    None),
    ("Snowberry", 5,  "transplant", "Plant container stock"),
    ("Snowberry", 6,  "growing",    "Small pink-white flowers Jun–Jul"),
    ("Snowberry", 7,  "growing",    "Blooming continues"),
    ("Snowberry", 8,  "growing",    "White berries forming"),
    ("Snowberry", 9,  "growing",    "Berries persist through winter"),
    ("Snowberry", 10, "dormant",    None),
    ("Snowberry", 11, "dormant",    None),
    ("Snowberry", 12, "dormant",    None),

    # Elderberry
    ("Elderberry", 1,  "dormant",    None),
    ("Elderberry", 2,  "dormant",    None),
    ("Elderberry", 3,  "pruning",    "Remove dead wood; thin oldest canes"),
    ("Elderberry", 4,  "dormant",    None),
    ("Elderberry", 5,  "transplant", "Plant in moist site"),
    ("Elderberry", 6,  "growing",    "Large white flower clusters — edible"),
    ("Elderberry", 7,  "harvest",    "Harvest flowers for cordial/fritters"),
    ("Elderberry", 8,  "harvest",    "Dark purple berries ripening Aug–Sep"),
    ("Elderberry", 9,  "harvest",    "Finish berry harvest; cook before eating"),
    ("Elderberry", 10, "dormant",    None),
    ("Elderberry", 11, "dormant",    None),
    ("Elderberry", 12, "dormant",    None),

    # Highbush Cranberry
    ("Highbush Cranberry", 1,  "dormant",    "Berries may persist on branches"),
    ("Highbush Cranberry", 2,  "dormant",    None),
    ("Highbush Cranberry", 3,  "pruning",    "Light pruning if needed"),
    ("Highbush Cranberry", 4,  "dormant",    None),
    ("Highbush Cranberry", 5,  "transplant", "Plant; white flower clusters May–Jun"),
    ("Highbush Cranberry", 6,  "growing",    "Blooming"),
    ("Highbush Cranberry", 7,  "growing",    "Fruit developing"),
    ("Highbush Cranberry", 8,  "growing",    "Berries turning red"),
    ("Highbush Cranberry", 9,  "harvest",    "Harvest after first frost for best flavour"),
    ("Highbush Cranberry", 10, "harvest",    "Continue harvest; berries persist"),
    ("Highbush Cranberry", 11, "dormant",    None),
    ("Highbush Cranberry", 12, "dormant",    None),

    # Wolf Willow
    ("Wolf Willow", 1,  "dormant",    None),
    ("Wolf Willow", 2,  "dormant",    None),
    ("Wolf Willow", 3,  "dormant",    None),
    ("Wolf Willow", 4,  "dormant",    None),
    ("Wolf Willow", 5,  "transplant", "Plant; intensely fragrant yellow flowers May–Jun"),
    ("Wolf Willow", 6,  "growing",    "Blooming; silvery foliage emerging"),
    ("Wolf Willow", 7,  "growing",    None),
    ("Wolf Willow", 8,  "growing",    None),
    ("Wolf Willow", 9,  "growing",    None),
    ("Wolf Willow", 10, "dormant",    None),
    ("Wolf Willow", 11, "dormant",    None),
    ("Wolf Willow", 12, "dormant",    None),

    # Haskap (Blue Honeysuckle)
    ("Haskap (Blue Honeysuckle)", 1,  "dormant",    None),
    ("Haskap (Blue Honeysuckle)", 2,  "dormant",    None),
    ("Haskap (Blue Honeysuckle)", 3,  "pruning",    "Light thinning prune"),
    ("Haskap (Blue Honeysuckle)", 4,  "dormant",    "Very early leaf-out"),
    ("Haskap (Blue Honeysuckle)", 5,  "transplant", "Plant; blooms Apr–May"),
    ("Haskap (Blue Honeysuckle)", 6,  "harvest",    "Earliest fruit! Harvest dark blue berries in June"),
    ("Haskap (Blue Honeysuckle)", 7,  "growing",    None),
    ("Haskap (Blue Honeysuckle)", 8,  "growing",    None),
    ("Haskap (Blue Honeysuckle)", 9,  "growing",    None),
    ("Haskap (Blue Honeysuckle)", 10, "dormant",    None),
    ("Haskap (Blue Honeysuckle)", 11, "dormant",    None),
    ("Haskap (Blue Honeysuckle)", 12, "dormant",    None),

    # ═══════════════════════════════════════════════════════════════════════
    # HERBS & PERENNIALS
    # ═══════════════════════════════════════════════════════════════════════

    # Comfrey
    ("Comfrey", 1,  "dormant",       None),
    ("Comfrey", 2,  "dormant",       None),
    ("Comfrey", 3,  "start_indoors", "Start root cuttings indoors in pots"),
    ("Comfrey", 4,  "start_indoors", "Continue indoor growth"),
    ("Comfrey", 5,  "transplant",    "Transplant root divisions after last frost"),
    ("Comfrey", 6,  "growing",       "Rapid growth; first chop-and-drop mulch"),
    ("Comfrey", 7,  "harvest",       "Cut leaves 2–3 times for mulch/compost tea"),
    ("Comfrey", 8,  "harvest",       "Continue cutting; leaves regrow quickly"),
    ("Comfrey", 9,  "growing",       "Final cut before dormancy"),
    ("Comfrey", 10, "dormant",       "Dies back to ground"),
    ("Comfrey", 11, "dormant",       None),
    ("Comfrey", 12, "dormant",       None),

    # Yarrow
    ("Yarrow", 1,  "dormant",       None),
    ("Yarrow", 2,  "dormant",       None),
    ("Yarrow", 3,  "start_indoors", "Surface-sow seeds indoors (needs light)"),
    ("Yarrow", 4,  "start_indoors", "Grow on under lights"),
    ("Yarrow", 5,  "transplant",    "Transplant or direct-sow after last frost"),
    ("Yarrow", 6,  "growing",       "Blooming begins mid-June"),
    ("Yarrow", 7,  "harvest",       "Harvest flowers for drying/tea"),
    ("Yarrow", 8,  "harvest",       "Continuous bloom; deadhead for more"),
    ("Yarrow", 9,  "growing",       "Blooms tapering off"),
    ("Yarrow", 10, "dormant",       None),
    ("Yarrow", 11, "dormant",       None),
    ("Yarrow", 12, "dormant",       None),

    # Bee Balm (Wild Bergamot)
    ("Bee Balm (Wild Bergamot)", 1,  "dormant",       None),
    ("Bee Balm (Wild Bergamot)", 2,  "dormant",       None),
    ("Bee Balm (Wild Bergamot)", 3,  "start_indoors", "Cold-stratify then start indoors"),
    ("Bee Balm (Wild Bergamot)", 4,  "start_indoors", "Grow on under lights"),
    ("Bee Balm (Wild Bergamot)", 5,  "transplant",    "Transplant after last frost"),
    ("Bee Balm (Wild Bergamot)", 6,  "growing",       "Vegetative growth"),
    ("Bee Balm (Wild Bergamot)", 7,  "growing",       "Lavender blooms — bee magnet"),
    ("Bee Balm (Wild Bergamot)", 8,  "harvest",       "Harvest flowers/leaves for tea"),
    ("Bee Balm (Wild Bergamot)", 9,  "growing",       "Leave seed heads for birds"),
    ("Bee Balm (Wild Bergamot)", 10, "dormant",       None),
    ("Bee Balm (Wild Bergamot)", 11, "dormant",       None),
    ("Bee Balm (Wild Bergamot)", 12, "dormant",       None),

    # Purple Coneflower
    ("Purple Coneflower", 1,  "dormant",       None),
    ("Purple Coneflower", 2,  "dormant",       None),
    ("Purple Coneflower", 3,  "start_indoors", "Start seeds indoors; needs cold stratification"),
    ("Purple Coneflower", 4,  "start_indoors", "Grow seedlings under lights"),
    ("Purple Coneflower", 5,  "transplant",    "Transplant after last frost"),
    ("Purple Coneflower", 6,  "growing",       "Vegetative growth"),
    ("Purple Coneflower", 7,  "growing",       "Blooming begins mid-July"),
    ("Purple Coneflower", 8,  "harvest",       "Harvest flowers/roots medicinally"),
    ("Purple Coneflower", 9,  "growing",       "Leave seed heads for finches"),
    ("Purple Coneflower", 10, "dormant",       None),
    ("Purple Coneflower", 11, "dormant",       None),
    ("Purple Coneflower", 12, "dormant",       None),

    # Chives
    ("Chives", 1,  "dormant",       None),
    ("Chives", 2,  "start_indoors", "Start seeds indoors 8–10 weeks before last frost"),
    ("Chives", 3,  "start_indoors", "Grow on under lights"),
    ("Chives", 4,  "start_indoors", "Harden off late April"),
    ("Chives", 5,  "transplant",    "Transplant or direct-sow; divide existing clumps"),
    ("Chives", 6,  "harvest",       "Harvest leaves and purple flowers"),
    ("Chives", 7,  "harvest",       "Cut regularly — regrows quickly"),
    ("Chives", 8,  "harvest",       "Continue harvesting"),
    ("Chives", 9,  "harvest",       "Final harvest before frost"),
    ("Chives", 10, "dormant",       None),
    ("Chives", 11, "dormant",       None),
    ("Chives", 12, "dormant",       None),

    # Horseradish
    ("Horseradish", 1,  "dormant",    None),
    ("Horseradish", 2,  "dormant",    None),
    ("Horseradish", 3,  "dormant",    None),
    ("Horseradish", 4,  "dormant",    "Prepare root cuttings"),
    ("Horseradish", 5,  "transplant", "Plant root cuttings 2–3 weeks before last frost"),
    ("Horseradish", 6,  "growing",    "Vigorous leaf growth"),
    ("Horseradish", 7,  "growing",    None),
    ("Horseradish", 8,  "growing",    None),
    ("Horseradish", 9,  "growing",    None),
    ("Horseradish", 10, "harvest",    "Dig roots after first hard frost for best flavour"),
    ("Horseradish", 11, "harvest",    "Continue harvest; roots store well in ground"),
    ("Horseradish", 12, "dormant",    None),

    # Rhubarb
    ("Rhubarb", 1,  "dormant",       None),
    ("Rhubarb", 2,  "start_indoors", "Start seeds indoors (slow germination)"),
    ("Rhubarb", 3,  "start_indoors", "Grow on under lights"),
    ("Rhubarb", 4,  "dormant",       "Prepare planting site with compost"),
    ("Rhubarb", 5,  "transplant",    "Plant crowns/divisions after soil thaws"),
    ("Rhubarb", 6,  "harvest",       "Harvest stalks June–July; pull, don't cut"),
    ("Rhubarb", 7,  "harvest",       "Stop harvest by late July to let plant recover"),
    ("Rhubarb", 8,  "growing",       "Let foliage grow to build root reserves"),
    ("Rhubarb", 9,  "growing",       "Remove flower stalks if they appear"),
    ("Rhubarb", 10, "dormant",       "Mulch with compost after frost"),
    ("Rhubarb", 11, "dormant",       None),
    ("Rhubarb", 12, "dormant",       None),

    # Lovage
    ("Lovage", 1,  "dormant",       None),
    ("Lovage", 2,  "start_indoors", "Start seeds indoors"),
    ("Lovage", 3,  "start_indoors", "Grow on under lights"),
    ("Lovage", 4,  "start_indoors", "Harden off"),
    ("Lovage", 5,  "transplant",    "Transplant after last frost"),
    ("Lovage", 6,  "harvest",       "Harvest leaves for celery-like flavour"),
    ("Lovage", 7,  "harvest",       "Flowers attract beneficial wasps"),
    ("Lovage", 8,  "harvest",       "Harvest seeds and leaves"),
    ("Lovage", 9,  "growing",       None),
    ("Lovage", 10, "dormant",       "Dies back to ground"),
    ("Lovage", 11, "dormant",       None),
    ("Lovage", 12, "dormant",       None),

    # Wild Mint
    ("Wild Mint", 1,  "dormant",    None),
    ("Wild Mint", 2,  "dormant",    None),
    ("Wild Mint", 3,  "dormant",    None),
    ("Wild Mint", 4,  "dormant",    None),
    ("Wild Mint", 5,  "transplant", "Plant divisions in moist soil"),
    ("Wild Mint", 6,  "growing",    "Spreading via runners"),
    ("Wild Mint", 7,  "harvest",    "Harvest leaves before flowering for best flavour"),
    ("Wild Mint", 8,  "harvest",    "Blooming Jul–Sep; still harvest leaves"),
    ("Wild Mint", 9,  "harvest",    "Final harvest before frost"),
    ("Wild Mint", 10, "dormant",    None),
    ("Wild Mint", 11, "dormant",    None),
    ("Wild Mint", 12, "dormant",    None),

    # Prairie Crocus
    ("Prairie Crocus", 1,  "dormant",    None),
    ("Prairie Crocus", 2,  "dormant",    None),
    ("Prairie Crocus", 3,  "growing",    "One of the very first blooms — even through snow!"),
    ("Prairie Crocus", 4,  "growing",    "Peak bloom; silky purple flowers"),
    ("Prairie Crocus", 5,  "growing",    "Feathery seed heads forming"),
    ("Prairie Crocus", 6,  "growing",    None),
    ("Prairie Crocus", 7,  "dormant",    "Goes summer-dormant"),
    ("Prairie Crocus", 8,  "dormant",    None),
    ("Prairie Crocus", 9,  "dormant",    None),
    ("Prairie Crocus", 10, "dormant",    None),
    ("Prairie Crocus", 11, "dormant",    None),
    ("Prairie Crocus", 12, "dormant",    None),

    # Fireweed
    ("Fireweed", 1,  "dormant",       None),
    ("Fireweed", 2,  "dormant",       None),
    ("Fireweed", 3,  "start_indoors", "Start seeds indoors (tiny — surface sow)"),
    ("Fireweed", 4,  "start_indoors", "Grow on under lights"),
    ("Fireweed", 5,  "transplant",    "Transplant after last frost"),
    ("Fireweed", 6,  "growing",       "Rapid upward growth"),
    ("Fireweed", 7,  "harvest",       "Tall magenta spikes; harvest young shoots/flowers"),
    ("Fireweed", 8,  "harvest",       "Peak bloom; excellent bee plant"),
    ("Fireweed", 9,  "growing",       "Fluffy seeds dispersing"),
    ("Fireweed", 10, "dormant",       None),
    ("Fireweed", 11, "dormant",       None),
    ("Fireweed", 12, "dormant",       None),

    # Stinging Nettle
    ("Stinging Nettle", 1,  "dormant",       None),
    ("Stinging Nettle", 2,  "start_indoors", "Start seeds indoors; slow germinator"),
    ("Stinging Nettle", 3,  "start_indoors", "Grow on under lights"),
    ("Stinging Nettle", 4,  "start_indoors", "Harden off"),
    ("Stinging Nettle", 5,  "transplant",    "Transplant or divide existing plants"),
    ("Stinging Nettle", 6,  "harvest",       "Harvest young tops for tea/soup (use gloves!)"),
    ("Stinging Nettle", 7,  "harvest",       "Second cut for liquid fertiliser"),
    ("Stinging Nettle", 8,  "growing",       "Flowering; too tough to eat"),
    ("Stinging Nettle", 9,  "growing",       "Fall regrowth — can harvest again"),
    ("Stinging Nettle", 10, "dormant",       None),
    ("Stinging Nettle", 11, "dormant",       None),
    ("Stinging Nettle", 12, "dormant",       None),

    # Canada Goldenrod
    ("Canada Goldenrod", 1,  "dormant",       None),
    ("Canada Goldenrod", 2,  "dormant",       None),
    ("Canada Goldenrod", 3,  "start_indoors", "Start seeds indoors; cold-stratify first"),
    ("Canada Goldenrod", 4,  "start_indoors", "Grow on"),
    ("Canada Goldenrod", 5,  "transplant",    "Transplant or divide rhizomes"),
    ("Canada Goldenrod", 6,  "growing",       "Vegetative growth"),
    ("Canada Goldenrod", 7,  "growing",       "Stalks reaching full height"),
    ("Canada Goldenrod", 8,  "growing",       "Golden plumes begin blooming — critical late-season nectar"),
    ("Canada Goldenrod", 9,  "growing",       "Peak bloom; supports 100+ insect species"),
    ("Canada Goldenrod", 10, "dormant",       "Seed heads for winter bird food"),
    ("Canada Goldenrod", 11, "dormant",       None),
    ("Canada Goldenrod", 12, "dormant",       None),

    # Blanketflower
    ("Blanketflower", 1,  "dormant",       None),
    ("Blanketflower", 2,  "dormant",       None),
    ("Blanketflower", 3,  "start_indoors", "Start seeds indoors 6–8 weeks before last frost"),
    ("Blanketflower", 4,  "start_indoors", "Grow on; harden off late April"),
    ("Blanketflower", 5,  "transplant",    "Transplant after last frost; or direct-sow"),
    ("Blanketflower", 6,  "growing",       "Red-and-yellow daisies begin blooming"),
    ("Blanketflower", 7,  "growing",       "Continuous bloom all summer"),
    ("Blanketflower", 8,  "growing",       "Deadhead for more flowers"),
    ("Blanketflower", 9,  "growing",       "Blooms until hard frost"),
    ("Blanketflower", 10, "dormant",       None),
    ("Blanketflower", 11, "dormant",       None),
    ("Blanketflower", 12, "dormant",       None),

    # Harebell
    ("Harebell", 1,  "dormant",       None),
    ("Harebell", 2,  "dormant",       None),
    ("Harebell", 3,  "start_indoors", "Start seeds indoors; surface sow (needs light)"),
    ("Harebell", 4,  "start_indoors", "Grow on under lights"),
    ("Harebell", 5,  "transplant",    "Transplant after last frost"),
    ("Harebell", 6,  "growing",       "Foliage filling in"),
    ("Harebell", 7,  "growing",       "Blue-violet bell flowers begin"),
    ("Harebell", 8,  "growing",       "Continuous bloom"),
    ("Harebell", 9,  "growing",       "Blooms until frost"),
    ("Harebell", 10, "dormant",       None),
    ("Harebell", 11, "dormant",       None),
    ("Harebell", 12, "dormant",       None),

    # Wild Lupine
    ("Wild Lupine", 1,  "dormant",       None),
    ("Wild Lupine", 2,  "dormant",       None),
    ("Wild Lupine", 3,  "start_indoors", "Scarify then start indoors; or fall-sow outdoors"),
    ("Wild Lupine", 4,  "start_indoors", "Grow on; lupines dislike transplanting"),
    ("Wild Lupine", 5,  "transplant",    "Transplant carefully (taproot) or direct-sow"),
    ("Wild Lupine", 6,  "growing",       "Blue-purple flower spikes Jun–Jul"),
    ("Wild Lupine", 7,  "growing",       "Peak bloom"),
    ("Wild Lupine", 8,  "growing",       "Seed pods ripening"),
    ("Wild Lupine", 9,  "growing",       None),
    ("Wild Lupine", 10, "dormant",       None),
    ("Wild Lupine", 11, "dormant",       None),
    ("Wild Lupine", 12, "dormant",       None),

    # ═══════════════════════════════════════════════════════════════════════
    # GROUNDCOVER
    # ═══════════════════════════════════════════════════════════════════════

    # White Clover
    ("White Clover", 1,  "dormant",     None),
    ("White Clover", 2,  "dormant",     None),
    ("White Clover", 3,  "dormant",     None),
    ("White Clover", 4,  "dormant",     None),
    ("White Clover", 5,  "direct_sow",  "Broadcast seed after last frost; tamp in"),
    ("White Clover", 6,  "growing",     "Spreading; blooms begin"),
    ("White Clover", 7,  "growing",     "Continuous bloom — excellent bee forage"),
    ("White Clover", 8,  "growing",     "Mow if desired; regrows quickly"),
    ("White Clover", 9,  "growing",     "Still active until hard frost"),
    ("White Clover", 10, "dormant",     None),
    ("White Clover", 11, "dormant",     None),
    ("White Clover", 12, "dormant",     None),

    # Creeping Thyme
    ("Creeping Thyme", 1,  "dormant",       None),
    ("Creeping Thyme", 2,  "start_indoors", "Start tiny seeds indoors 8–10 weeks early"),
    ("Creeping Thyme", 3,  "start_indoors", "Surface sow; needs light to germinate"),
    ("Creeping Thyme", 4,  "start_indoors", "Harden off"),
    ("Creeping Thyme", 5,  "transplant",    "Transplant or divide existing plants"),
    ("Creeping Thyme", 6,  "growing",       "Purple blooms begin; very fragrant"),
    ("Creeping Thyme", 7,  "harvest",       "Harvest sprigs; peak essential oils"),
    ("Creeping Thyme", 8,  "harvest",       "Continue harvesting"),
    ("Creeping Thyme", 9,  "growing",       "Evergreen — persists into fall"),
    ("Creeping Thyme", 10, "dormant",       None),
    ("Creeping Thyme", 11, "dormant",       None),
    ("Creeping Thyme", 12, "dormant",       None),

    # Kinnikinnick (Bearberry)
    ("Kinnikinnick (Bearberry)", 1,  "dormant",    None),
    ("Kinnikinnick (Bearberry)", 2,  "dormant",    None),
    ("Kinnikinnick (Bearberry)", 3,  "dormant",    None),
    ("Kinnikinnick (Bearberry)", 4,  "dormant",    None),
    ("Kinnikinnick (Bearberry)", 5,  "transplant", "Plant container stock; slow to establish"),
    ("Kinnikinnick (Bearberry)", 6,  "growing",    "Small pink-white bells blooming"),
    ("Kinnikinnick (Bearberry)", 7,  "growing",    None),
    ("Kinnikinnick (Bearberry)", 8,  "growing",    "Red berries forming"),
    ("Kinnikinnick (Bearberry)", 9,  "harvest",    "Berries ripe — wildlife food"),
    ("Kinnikinnick (Bearberry)", 10, "growing",    "Evergreen foliage persists"),
    ("Kinnikinnick (Bearberry)", 11, "dormant",    None),
    ("Kinnikinnick (Bearberry)", 12, "dormant",    None),

    # Wild Strawberry
    ("Wild Strawberry", 1,  "dormant",       None),
    ("Wild Strawberry", 2,  "start_indoors", "Start seeds indoors; cold-stratify first"),
    ("Wild Strawberry", 3,  "start_indoors", "Grow on under lights; slow germination"),
    ("Wild Strawberry", 4,  "start_indoors", "Harden off"),
    ("Wild Strawberry", 5,  "transplant",    "Transplant or plant runners after last frost"),
    ("Wild Strawberry", 6,  "growing",       "White flowers; runners spreading"),
    ("Wild Strawberry", 7,  "harvest",       "Harvest tiny intensely flavoured berries"),
    ("Wild Strawberry", 8,  "growing",       "Runners extending ground coverage"),
    ("Wild Strawberry", 9,  "growing",       None),
    ("Wild Strawberry", 10, "dormant",       "Mulch for winter protection"),
    ("Wild Strawberry", 11, "dormant",       None),
    ("Wild Strawberry", 12, "dormant",       None),

    # Alfalfa
    ("Alfalfa", 1,  "dormant",    None),
    ("Alfalfa", 2,  "dormant",    None),
    ("Alfalfa", 3,  "dormant",    None),
    ("Alfalfa", 4,  "dormant",    None),
    ("Alfalfa", 5,  "direct_sow", "Broadcast seed after last frost; inoculate with rhizobia"),
    ("Alfalfa", 6,  "growing",    "Rapid growth; nitrogen fixation active"),
    ("Alfalfa", 7,  "harvest",    "First cut for green mulch/chop-and-drop"),
    ("Alfalfa", 8,  "harvest",    "Second cut; purple flowers if left"),
    ("Alfalfa", 9,  "growing",    "Don't cut after Sep 1 — let roots store energy"),
    ("Alfalfa", 10, "dormant",    None),
    ("Alfalfa", 11, "dormant",    None),
    ("Alfalfa", 12, "dormant",    None),

    # ═══════════════════════════════════════════════════════════════════════
    # VINES
    # ═══════════════════════════════════════════════════════════════════════

    # Hops
    ("Hops", 1,  "dormant",       None),
    ("Hops", 2,  "start_indoors", "Start rhizome cuttings indoors in pots"),
    ("Hops", 3,  "start_indoors", "Grow on; prepare trellis/support"),
    ("Hops", 4,  "dormant",       "Install trellis if not in place"),
    ("Hops", 5,  "transplant",    "Plant rhizomes after last frost; train up strings"),
    ("Hops", 6,  "growing",       "Explosive growth — up to 15 cm/day"),
    ("Hops", 7,  "growing",       "Cones forming on female plants"),
    ("Hops", 8,  "harvest",       "Harvest hops when papery and fragrant"),
    ("Hops", 9,  "harvest",       "Finish harvest; cut bines to ground after frost"),
    ("Hops", 10, "dormant",       "Mulch root zone"),
    ("Hops", 11, "dormant",       None),
    ("Hops", 12, "dormant",       None),

    # Virginia Creeper
    ("Virginia Creeper", 1,  "dormant",    None),
    ("Virginia Creeper", 2,  "dormant",    None),
    ("Virginia Creeper", 3,  "dormant",    None),
    ("Virginia Creeper", 4,  "dormant",    None),
    ("Virginia Creeper", 5,  "transplant", "Plant container stock; attach to support"),
    ("Virginia Creeper", 6,  "growing",    "Rapid growth; self-clinging tendrils"),
    ("Virginia Creeper", 7,  "growing",    None),
    ("Virginia Creeper", 8,  "growing",    None),
    ("Virginia Creeper", 9,  "growing",    "Spectacular crimson fall colour"),
    ("Virginia Creeper", 10, "dormant",    "Berries for birds; leaf drop"),
    ("Virginia Creeper", 11, "dormant",    None),
    ("Virginia Creeper", 12, "dormant",    None),

    # Hardy Kiwi
    ("Hardy Kiwi", 1,  "dormant",    None),
    ("Hardy Kiwi", 2,  "dormant",    None),
    ("Hardy Kiwi", 3,  "pruning",    "Prune in late winter while dormant"),
    ("Hardy Kiwi", 4,  "dormant",    "Install strong pergola or trellis"),
    ("Hardy Kiwi", 5,  "transplant", "Plant after last frost; fragrant white flowers May–Jun"),
    ("Hardy Kiwi", 6,  "growing",    "Very vigorous growth; train on support"),
    ("Hardy Kiwi", 7,  "growing",    "Summer prune to control vigour"),
    ("Hardy Kiwi", 8,  "growing",    "Fruit developing"),
    ("Hardy Kiwi", 9,  "harvest",    "Harvest grape-sized kiwis Sep–Oct"),
    ("Hardy Kiwi", 10, "harvest",    "Finish harvest before hard frost"),
    ("Hardy Kiwi", 11, "dormant",    None),
    ("Hardy Kiwi", 12, "dormant",    None),

    # ═══════════════════════════════════════════════════════════════════════
    # ROOT / BULB
    # ═══════════════════════════════════════════════════════════════════════

    # Garlic
    ("Garlic", 1,  "dormant",       "Overwintering underground"),
    ("Garlic", 2,  "dormant",       None),
    ("Garlic", 3,  "dormant",       "Order seed garlic for fall planting"),
    ("Garlic", 4,  "growing",       "Shoots emerge through soil/mulch"),
    ("Garlic", 5,  "growing",       "Rapid leaf growth; keep weeded"),
    ("Garlic", 6,  "harvest",       "Harvest scapes (curly tops) for pesto"),
    ("Garlic", 7,  "harvest",       "Main harvest when lower leaves yellow"),
    ("Garlic", 8,  "growing",       "Cure harvested bulbs 2–3 weeks in dry shade"),
    ("Garlic", 9,  "growing",       "Prepare beds for fall planting"),
    ("Garlic", 10, "direct_sow",    "Plant cloves 4–6 weeks before ground freezes"),
    ("Garlic", 11, "dormant",       "Mulch heavily after ground freezes"),
    ("Garlic", 12, "dormant",       None),

    # Jerusalem Artichoke
    ("Jerusalem Artichoke", 1,  "dormant",     None),
    ("Jerusalem Artichoke", 2,  "dormant",     None),
    ("Jerusalem Artichoke", 3,  "dormant",     None),
    ("Jerusalem Artichoke", 4,  "dormant",     "Prepare planting site; can contain with barrier"),
    ("Jerusalem Artichoke", 5,  "direct_sow",  "Plant tubers 10 cm deep after last frost"),
    ("Jerusalem Artichoke", 6,  "growing",     "Rapid vertical growth"),
    ("Jerusalem Artichoke", 7,  "growing",     "Stalks reaching 2–3 m tall"),
    ("Jerusalem Artichoke", 8,  "growing",     None),
    ("Jerusalem Artichoke", 9,  "growing",     "Yellow sunflowers Sep–Oct; late bee food"),
    ("Jerusalem Artichoke", 10, "harvest",     "Dig tubers after first hard frost"),
    ("Jerusalem Artichoke", 11, "harvest",     "Continue digging; tubers store in ground"),
    ("Jerusalem Artichoke", 12, "dormant",     "Leave some tubers for next year"),
]
