"""
tools/local_flora_review/reads.py -- a read of each species the Edmonton rule
cannot settle (V3.12).

**Opinion, not data.** Written by Claude from memory of the regional floras, to
give the owner something to argue with on the review page, which labels every
one "My read, from memory". Nothing in the app or on the website reads this
file; the owner's rulings are what count, and they live in
``data/local_flora_rulings.json``.

``native`` = likely native around Edmonton, ``not`` = likely not, ``unsure``.
"""

READS = {
    # ---- 1-2 collections within 50 km ----
    "Viburnum opulus": ("native", "The native race (subsp. trilobum) grows in moist river-valley woods and ravines. The observations mix it with the European race planted in yards."),
    "Fragaria vesca": ("native", "A woodland strawberry of aspen and mixed woods across central Alberta."),
    "Salix interior": ("native", "Forms thickets on the North Saskatchewan's sandbars and banks."),
    "Glycyrrhiza lepidota": ("native", "A plant of moist prairie, slough margins and river flats in the parkland."),
    "Penstemon procerus": ("unsure", "Common in southern and western Alberta grassland. How far into the Edmonton parkland it reaches I can't say from memory, and it is often planted."),
    "Geum triflorum": ("native", "A parkland grassland plant; the remnant native grassland around Edmonton is where it belongs."),
    "Blitum capitatum": ("native", "Comes up on disturbed ground, clearings and burns across the province."),
    "Primula pauciflora": ("native", "Moist and saline meadows of the prairie and parkland."),
    "Monarda fistulosa": ("native", "A parkland and prairie plant of open slopes. Also widely planted, which inflates the observations."),
    "Oenothera biennis": ("native", "A weedy native of disturbed and sandy ground across the parkland."),
    "Thermopsis rhombifolia": ("unsure", "Common on sandy prairie and parkland further south; I can't place its northern edge relative to Edmonton."),
    "Alisma triviale": ("native", "Marshes, ponds and ditches throughout."),
    "Linum lewisii": ("unsure", "Dry grassland and slopes. Planted often enough that the observations prove little."),
    "Juniperus communis": ("unsure", "Dry open pine and spruce woods. Possible on sandy ground within 50 km, but I can't place it."),
    "Geum rivale": ("native", "Wet meadows and fens of the parkland and the boreal edge."),
    "Equisetum hyemale": ("native", "Sandy riverbanks and moist slopes; the river valley is its habitat."),
    "Maianthemum amplexicaule": ("unsure", "Moist woods, more common south and west; I can't say whether it reaches Edmonton."),
    "Menyanthes trifoliata": ("native", "Bogs, fens and pond margins; there are fens within 50 km."),
    "Muhlenbergia cuspidata": ("unsure", "A grass of dry, eroded prairie slopes. The 1931 and 1966 sheets could be from the river valley's dry banks."),
    "Solidago lepida": ("native", "Most herbaria file it under Solidago canadensis, and 32 collections around Edmonton carry that name. VASCAN does not record S. canadensis in Alberta, so those sheets are most likely this plant."),
    "Bolboschoenus maritimus": ("unsure", "Saline and alkaline marshes. There are saline sloughs east of the city, but I can't confirm it from memory."),
    "Carex pellita": ("native", "Wet meadows and marsh edges; common through the parkland."),
    "Antennaria rosea": ("unsure", "Widespread in dry open places, but pussytoes are hard to tell apart, so the sheets matter more than usual."),
    "Betula occidentalis": ("unsure", "Streambanks, mostly in the south and the foothills."),
    "Physostegia ledinghamii": ("unsure", "A rare plant of moist meadows and streambanks; I can't place it."),
    "Equisetum variegatum": ("native", "Wet sandy ground, fens and riverbanks; widespread."),
    "Piptatherum canadense": ("unsure", "Dry sandy jack pine woods of the boreal. Possible on the sandy ground at the circle's edge."),
    "Carex rostrata": ("native", "Fens and marshes throughout."),
    "Thalictrum occidentale": ("unsure", "A foothills and mountain meadowrue. Edmonton's common one is veiny meadowrue, which it can be mistaken for."),
    "Allium textile": ("unsure", "Dry prairie and slopes. Possible on the river valley's dry south-facing banks."),
    "Arnica fulgens": ("unsure", "A plant of fescue grassland, which once covered parts of the region."),
    "Carex lacustris": ("native", "Marshes and swamps of the parkland and boreal."),
    "Danthonia spicata": ("unsure", "Dry open woods on sandy ground. Possible here, not certain."),
    "Sorbus scopulina": ("not", "A foothills and mountain shrub. Two recent sheets (2009, 2013) fit a planted or escaped tree."),
    "Prunus pensylvanica": ("native", "A shrub of aspen woods and clearings across central Alberta; one sheet undersells it badly."),
    "Shepherdia argentea": ("not", "Native in southern coulees and river valleys. Around Edmonton it is a shelterbelt shrub."),
    "Opuntia fragilis": ("unsure", "It reaches surprisingly far north on dry slopes, but I can't confirm a wild population near Edmonton, and garden plants are common."),
    "Dalea purpurea": ("unsure", "A mixed-grass prairie plant. The one sheet is from 1938, and native gardens plant it widely."),
    "Veronica americana": ("native", "Stream edges and wet ground throughout."),
    "Dasiphora fruticosa": ("native", "Native in fens and wet meadows. The cultivars planted in yards inflate the observations."),
    "Matteuccia struthiopteris": ("native", "Moist floodplain woods along rivers in the boreal and parkland."),
    "Nuphar variegata": ("native", "Lakes and ponds throughout."),
    "Cerastium arvense": ("native", "Dry grassland and open slopes across the province."),
    "Comarum palustre": ("native", "Fens and marsh edges."),
    "Castilleja miniata": ("unsure", "Moist meadows and open woods, mostly west and north; I can't place it near Edmonton."),
    "Achillea borealis": ("native", "The native yarrow. Nine more collections around Edmonton are filed under Achillea millefolium, which this catalogue merged into it in V2.80."),
    "Drymocallis arguta": ("native", "Dry to moist open ground across the prairie, parkland and boreal edge."),
    "Rosa arkansana": ("native", "The low prairie rose of parkland grassland."),
    "Juniperus horizontalis": ("unsure", "Sandy and gravelly ground. Possible within 50 km, and widely planted."),
    "Potentilla gracilis": ("native", "Meadows and open woods; widespread."),
    "Arnica chamissonis": ("unsure", "Moist meadows and streambanks. The only sheet is from 1917."),
    "Vaccinium oxycoccos": ("native", "Sphagnum bogs; there are bogs within 50 km."),
    "Spartina gracilis": ("unsure", "Saline meadows, mostly further south."),
    "Anticlea elegans": ("unsure", "Moist meadows and fens across the province; plausible here."),
    "Potentilla pensylvanica": ("unsure", "Dry grassland; plausible on dry slopes."),
    "Erigeron speciosus": ("not", "A foothills and mountain fleabane. One 1946 sheet and a few observations, which may be garden plants."),
    "Avenula hookeri": ("unsure", "A grass of fescue grassland. The one sheet is from 1943."),
    "Distichlis spicata": ("unsure", "Saline flats, mostly further south."),
    "Solanum triflorum": ("unsure", "A native of disturbed prairie soil. One 1948 sheet."),
    "Bolboschoenus fluviatilis": ("unsure", "Rare in Alberta. One 2013 sheet."),
    "Calamovilfa longifolia": ("not", "A grass of the southern sand hills. The cache holds only 13 records of it, and the one here is a sheet from 1914."),
    "Carex raymondii": ("unsure", "I can't place this sedge from memory."),
    "Elymus glaucus": ("not", "A grass of foothills and mountain woods."),
    "Elymus lanceolatus": ("unsure", "Prairie and sandy ground. Under-collected, so one sheet proves little either way."),
    "Erigeron caespitosus": ("unsure", "Dry eroded slopes and badlands, mostly in the south."),
    "Festuca campestris": ("not", "The foothills rough fescue. Edmonton's is plains rough fescue (Festuca hallii), which the 2017 sheet may be."),
    "Gentiana affinis": ("unsure", "Moist prairie meadows. One 1936 sheet."),
    "Helianthus maximiliani": ("not", "A plant of the eastern prairies. One sheet, from 1927."),
    "Mahonia repens": ("not", "A mountain shrub of the southwest; garden plants are the likely source."),
    "Oxytropis monticola": ("unsure", "Grassland and foothills. One 1933 sheet."),
    "Peritoma serrulata": ("not", "A plant of dry southern disturbed ground. One sheet, from 1939."),
    "Poa alpina": ("not", "An alpine grass."),
    "Prunella vulgaris": ("unsure", "The native race grows in moist woods; the lawn weed is the introduced one, and the records don't separate them."),
    # ---- seen within 50 km, never collected there ----
    "Ribes aureum": ("not", "Native in southern coulees; planted in Edmonton yards."),
    "Oxytropis campestris": ("unsure", "Grassland and slopes; I can't place it near Edmonton."),
    "Spiraea alba": ("unsure", "Rare in Alberta, on wet boreal ground. The observations may be garden spireas."),
    "Hedysarum boreale": ("unsure", "Prairie and foothills slopes; the nearest record outside the circle is 102 km away."),
    "Oenothera suffrutescens": ("not", "A plant of dry southern prairie; the observations are probably garden plants."),
    "Ribes lacustre": ("unsure", "Moist woods, mostly in the foothills and boreal."),
    "Astragalus canadensis": ("native", "Moist meadows and open woods of the parkland."),
    "Astragalus laxmannii": ("unsure", "Prairie and parkland grassland; plausible."),
    "Ratibida columnifera": ("not", "A southern prairie plant, widely sown in wildflower mixes."),
    "Pinus contorta": ("not", "A foothills and mountain pine, planted in the city."),
    "Potentilla hippiana": ("unsure", "Dry prairie; plausible on dry slopes."),
    "Asclepias speciosa": ("not", "In Alberta a plant of the far southeast; planted for monarchs."),
    "Oenothera nuttallii": ("not", "A plant of the southern sand hills."),
    "Abies balsamea": ("not", "A tree of the mixedwood boreal north of here; in Edmonton it is planted."),
    "Sphaeralcea coccinea": ("unsure", "Dry prairie and disturbed ground; I can't say whether it reaches Edmonton."),
    "Eutrochium maculatum": ("unsure", "Wet meadows. Uncommon in Alberta, and often planted."),
    "Coreopsis tinctoria": ("not", "A plant of southern sloughs and disturbed ground, sown in wildflower mixes."),
    "Penstemon gracilis": ("unsure", "Prairie and parkland grassland; plausible."),
    "Juniperus scopulorum": ("not", "A tree of the southwest mountains and valleys."),
    "Sagittaria latifolia": ("unsure", "Rare in Alberta, where arum-leaved arrowhead is the common one."),
    "Viola pedatifida": ("unsure", "Prairie and parkland grassland; plausible."),
    "Anaphalis margaritacea": ("unsure", "Disturbed ground in the foothills and boreal. One observation."),
    "Delphinium glaucum": ("unsure", "Moist woods and meadows, mostly west and north."),
    "Eriocoma hymenoides": ("not", "A grass of dry southern sand."),
    "Hesperostipa spartea": ("unsure", "A grass of moist mixed-grass prairie. The cache holds only 24 records of it anywhere, so its absence here says little."),
    "Opuntia polyacantha": ("not", "A cactus of the dry south."),
    "Penstemon confertus": ("not", "A mountain penstemon of the southwest."),
    "Penstemon nitidus": ("not", "A plant of dry southern prairie."),
    "Pseudotsuga menziesii": ("not", "A tree of the southwest mountains."),
    "Solidago glutinosa": ("unsure", "Twelve collections within 50 km, all from 1917 to 1944, are filed under Solidago simplex, a name this catalogue retired in V2.80. Nothing since, and one observation: worth seeing the sheets."),
    # ---- no records in the cache at all ----
    "Elodea canadensis": ("native", "A pond and lake plant found throughout. The cache holds no records of it, which is a gap in the harvest, not in the plant."),
    "Oenothera cespitosa": ("not", "A plant of dry southern badlands."),
    "Penstemon lyallii": ("not", "A mountain penstemon of the southwest."),
    # ---- passed the rule, flagged ----
    "Acer negundo": ("not", "Passes the rule with 14 collections from 1933 to 2008, 10 of them within 7 km of downtown. As I remember the floras, Alberta's wild Manitoba maples are in southern river valleys and Edmonton's descend from plantings; if so, these are sheets of planted or escaped trees."),
    "Poa secunda": ("unsure", "Passes the rule with 8 collections, but from a few spots revisited over the years (10 km out in 1991, 2001 and 2006; 46 km out in 2001 and 2004), which looks like a monitoring plot. It may well be native on dry slopes: flagged for a look, not for removal."),
}

FLAGGED = ("Acer negundo", "Poa secunda")
